<?php
/*
 * @file code for obiba_mica_angular_search module
 * */

function obiba_mica_angular_search_menu() {
  $items = array();

//  $items['mica/angular-search'] = array(
//    'title' => 'Angular Search',
//    'description' => 'Angular Search',
//    'page callback' => 'obiba_mica_angular_search_variable_page_search',
//    'menu_name' => 'main-menu',
//    'weight' => 12,
//    'access callback' => TRUE
//  );

  $items['mica/search/taxonomies/_search/ws'] = array(
    'page callback' => 'obiba_mica_angular_search_taxonomies_search',
    'file' => 'obiba_mica_angular_search_services.inc',
    'access callback' => TRUE
  );
  $items['mica/search/taxonomies/_filter/ws'] = array(
    'page callback' => 'obiba_mica_angular_search_taxonomies_filter',
    'file' => 'obiba_mica_angular_search_services.inc',
    'access callback' => TRUE
  );
  $items['mica/search/taxonomy/%/_filter/ws'] = array(
    'page callback' => 'obiba_mica_angular_search_get_taxonomy',
    'file' => 'obiba_mica_angular_search_services.inc',
    'page arguments' => array(2),
    'access callback' => TRUE
  );
  $items['mica/search/taxonomy/%/vocabulary/%/_filter/ws'] = array(
    'page callback' => 'obiba_mica_angular_search_get_vocabulary',
    'file' => 'obiba_mica_angular_search_services.inc',
    'page arguments' => array(2),
    'access callback' => TRUE
  );
  $items['mica/search/%/_rql/%/ws'] = array(
    'page callback' => 'obiba_mica_angular_search_query',
    'file' => 'obiba_mica_angular_search_services.inc',
    'page arguments' => array(2, 4),
    'access callback' => TRUE
  );

  return $items;
}

/**
 * Implements hook_get_js().
 */
function obiba_mica_angular_search_get_js($weight_js) {
  if (current_path() == MicaClientPathProvider::ANGULAR_SEARCH) {
    $module_path = drupal_get_path('module', 'obiba_mica_angular_search');
    $js = file_scan_directory($module_path . '/js/app', '/.*\.js$/', array('key' => 'name'));
    ksort($js);
    foreach ($js as $file_js) {
      drupal_add_js($file_js->uri, array(
        'type' => 'file',
        'scope' => 'footer',
        'weight' => ++$weight_js,
      ));
    }
  }
  return ++$weight_js;
}

/**
 * Implements hook_load_menus().
 */
function obiba_mica_angular_search_load_menus() {
  $items = array();

  $items[MicaClientPathProvider::ANGULAR_SEARCH] = array(
    'access callback' => TRUE,
    'title' => variable_get('search_page_title', 'Search'),
    'module_caller' => 'obiba_mica_angular_search',
  );
  return $items;
}

/**
 * Implements hook_get_ng_module_to_load().
 */
function obiba_mica_angular_search_get_ng_module_to_load() {
  if (current_path() == MicaClientPathProvider::ANGULAR_SEARCH) {
    return 'mica.ObibaSearch';
  }
  return FALSE;
}

/**
 * Implements hook_theme().
 */
function obiba_mica_angular_search_theme($existing, $type, $theme, $path) {
  $path_template = $path . '/templates';
  $path_views = $path . '/js/app/views';
  return array(
    'obiba_mica_angular_search_main_app' => array(
      'template' => 'obiba_mica_angular_search_main_app',
      'path' => $path_template,
    ),
    'obiba_angular_search_view_header' => array(
      'template' => 'obiba_angular_search_view_header',
      'path' => $path_views,
    ),
  );

}

/**
 * Main Search page
 */
function obiba_mica_angular_search_variable_page_search() {
  return theme('obiba_mica_angular_search_main_app', array());
}

/**
 * Search Module settings
 */
function obiba_mica_angular_search_config() {
  return array(
    'networks' =>
      array(
        'showNetworksSearchTab' => variable_get_value('search_networks'),
        'networksColumn' => array(
          'showNetworksStudiesColumn' => variable_get_value('networks_column_studies'),
          'showNetworksStudyDatasetColumn' => variable_get_value('networks_column_study_datasets'),
          'showNetworksHarmonizedDatasetColumn' => variable_get_value('networks_column_harmonization_datasets'),
          'showNetworksVariablesColumn' => variable_get_value('networks_column_variables'),
        )
      ),
    'studies' =>
      array(
        'showStudiesSearchTab' => variable_get_value('search_studies'),
        'showStudiesSearchFilter' => variable_get_value('studies_facet_search'),
        'studiesColumn' => array(
          'showStudiesDesignColumn' => variable_get_value('studies_column_design'),
          'showStudiesQuestionnaireColumn' => variable_get_value('studies_column_questionnaire'),
          'showStudiesPmColumn' => variable_get_value('studies_column_pm'),
          'showStudiesBioColumn' => variable_get_value('studies_column_bio'),
          'showStudiesOtherColumn' => variable_get_value('studies_column_other'),
          'showStudiesParticipantsColumn' => variable_get_value('studies_column_participants'),
          'showStudiesNetworksColumn' => variable_get_value('studies_column_networks'),
          'showStudiesDatasetsColumn' => variable_get_value('studies_column_study_datasets'),
          'showStudiesHarmonizedDatasetsColumn' => variable_get_value('studies_column_harmonization_datasets'),
          'showStudiesVariablesColumn' => variable_get_value('studies_column_variables'),
        )
      ),
    'datasets' =>
      array(
        'showDatasetsSearchTab' => variable_get_value('search_datasets'),
        'showDatasetsSearchFilter' => variable_get_value('search_datasets_autocomplete'),
        'datasetsColumn' => array(
          'showDatasetsTypeColumn' => variable_get_value('datasets_column_type'),
          'showDatasetsNetworkColumn' => variable_get_value('datasets_column_networks'),
          'showDatasetsStudiesColumn' => variable_get_value('datasets_column_studies'),
          'showDatasetsVariablesColumn' => variable_get_value('datasets_column_variables'),
        )
      ),
    'variables' =>
      array(
        'showVariablesSearchTab' => variable_get_value('search_variables'),
        'variablesColumn' => array(
          'showVariablesStudiesColumn' => variable_get_value('variables_column_study'),
          'showVariablesDatasetsColumn' => variable_get_value('variables_column_dataset'),
          'showDatasetsStudiesColumn' => variable_get_value('datasets_column_studies'),
          'showDatasetsVariablesColumn' => variable_get_value('datasets_column_variables'),
        )
      )
  );
}
