<?php
/*
 * @file code for obiba_mica_angular_search module
 * */

function obiba_mica_angular_search_menu() {
  $items = array();

  $items['mica/' . ObibaSearchResources::MICA_SEARCH . '/taxonomies/_search/ws'] = array(
    'page callback' => 'obiba_mica_angular_search_taxonomies_search',
    'file' => 'obiba_mica_angular_search_services.inc',
    'access callback' => TRUE
  );
  $items['mica/' . ObibaSearchResources::MICA_SEARCH . '/taxonomies/_filter/ws'] = array(
    'page callback' => 'obiba_mica_angular_search_taxonomies_filter',
    'file' => 'obiba_mica_angular_search_services.inc',
    'access callback' => TRUE
  );
  $items['mica/' . ObibaSearchResources::MICA_SEARCH . '/taxonomy/%/_filter/ws'] = array(
    'page callback' => 'obiba_mica_angular_search_get_taxonomy',
    'file' => 'obiba_mica_angular_search_services.inc',
    'page arguments' => array(2),
    'access callback' => TRUE
  );
  $items['mica/' . ObibaSearchResources::MICA_SEARCH . '/taxonomy/%/vocabulary/%/_filter/ws'] = array(
    'page callback' => 'obiba_mica_angular_search_get_vocabulary',
    'file' => 'obiba_mica_angular_search_services.inc',
    'page arguments' => array(2),
    'access callback' => TRUE
  );
  $items['mica/' . ObibaSearchResources::MICA_SEARCH . '/%/_rql/%/ws'] = array(
    'page callback' => 'obiba_mica_angular_search_query',
    'file' => 'obiba_mica_angular_search_services.inc',
    'page arguments' => array(2, 4),
    'access callback' => TRUE
  );
  $items['mica/variables/_coverage/%/ws'] = array(
    'page callback' => 'obiba_mica_angular_search_variable_coverage',
    'file' => 'obiba_mica_angular_search_services.inc',
    'page arguments' => array(3),
    'access callback' => TRUE
  );

  return $items;
}

/**
 * Implements hook_get_js().
 */
function obiba_mica_angular_search_get_js($weight_js) {
  if (current_path() == MicaClientPathProvider::ANGULAR_SEARCH) {
    $module_path = drupal_get_path('module', 'obiba_mica_angular_search');
    $js = file_scan_directory($module_path . '/js/app', '/.*\.js$/', array('key' => 'name'));
    ksort($js);
    foreach ($js as $file_js) {
      drupal_add_js($file_js->uri, array(
        'type' => 'file',
        'scope' => 'footer',
        'weight' => ++$weight_js,
      ));
    }
  }
  return ++$weight_js;
}

/**
 * Implements hook_load_menus().
 */
function obiba_mica_angular_search_load_menus() {
  $items = array();

  $items[MicaClientPathProvider::ANGULAR_SEARCH] = array(
    'access callback' => TRUE,
    'title' => variable_get('search_page_title', 'Search'),
    'module_caller' => 'obiba_mica_angular_search',
  );
  return $items;
}

/**
 * Implements hook_get_ng_module_to_load().
 */
function obiba_mica_angular_search_get_ng_module_to_load() {
  if (current_path() == MicaClientPathProvider::ANGULAR_SEARCH) {
    return 'mica.ObibaSearch';
  }
  return FALSE;
}

/**
 * Implements hook_theme().
 */
function obiba_mica_angular_search_theme($existing, $type, $theme, $path) {
  $path_template = $path . '/templates';
  $path_views = $path . '/js/app/views';
  return array(
    'obiba_mica_angular_search_main_app' => array(
      'template' => 'obiba_mica_angular_search_main_app',
      'path' => $path_template,
    ),
    'obiba_angular_search_view_header' => array(
      'template' => 'obiba_angular_search_view_header',
      'path' => $path_views,
    ),
  );

}

/**
 * Main Search page
 */
function obiba_mica_angular_search_variable_page_search() {
  return theme('obiba_mica_angular_search_main_app', array());
}
