<?php
/*
 * Copyright (c) 2015 OBiBa. All rights reserved.
 *
 * This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

function obiba_main_app_angular_menu() {
  $external_items = array();
  $external_items += obiba_angular_load_external_menus_definitions();

  foreach ($external_items as $key_item => $external_item) {
    $external_items[$key_item]['page callback'] = 'obiba_main_app_angular_main_page';
  }
  $items = array();

  $items['obiba-angular-app'] = array(
    'page callback' => 'obiba_main_app_angular_main_page',
    'access callback' => TRUE,
    //'page arguments' => array(2)
  );

  $items['obiba_main_app_angular/%/%'] = array(
    'page callback' => 'obiba_main_app_angular_get_angular_template',
    'access callback' => TRUE,
    'page arguments' => array(1, 2)
  );
  return $items + $external_items;
}

/**
 * Implements hook_library().
 */
function obiba_main_app_angular_library() {
  return obiba_main_app_angular_load_angular_library();
}

/**
 * Implements hook_library_alter().
 * Angular library compatible with Jquery 1.10
 *
 */
function obiba_main_app_angular_library_alter(&$javascript, $module) {
  if (($module == 'obiba_main_app_angular' || $module == 'system') && current_path() == 'obiba-angular-app') {
    $path = drupal_get_path('module', 'jquery_update');
    jquery_update_jquery_replace($javascript, NULL, $path, NULL, '1.10');
  }

}

/**
 * Implements hook_theme().
 */
function obiba_main_app_angular_theme($existing, $type, $theme, $path) {
  $path_theme = $path . '/templates';
  //load external AngularJs app to implement their template folder
  return array(
    'obiba_angular_main' => array(
      'template' => 'obiba_angular_main',
      'path' => $path_theme
    )
  );
}

/**
 * hook implementations to load the menus rooting of external angular js modules
 */

function obiba_angular_load_external_menus_definitions() {
  $external_items = array();
  foreach (module_implements('load_menus') as $module) {
    $external_items += module_invoke($module, 'load_menus');
  }
  return $external_items;
}

/**
 * hook implementation to load external angular app js
 */
function obiba_main_app_angular_load_external_app_js() {
  module_invoke_all('get_js');
}

/**
 * hook implementation to get external modules names to load
 */
function obiba_main_app_angular_load_ng_module() {
  $modules = array();
  foreach (module_implements('get_ng_module_to_load') as $module) {
    // Calling all modules implementing hook_hook_name and
    // Returning results than pushing them into the $result array:
    $modules[] = module_invoke($module, 'get_ng_module_to_load');
  }
  return $modules;
}

function obiba_main_app_angular_load_js_resources() {
  obiba_main_app_angular_load_libraires_resources('obiba_main_app_angular');
  $module_path = drupal_get_path('module', 'obiba_main_app_angular');
  $js = file_scan_directory($module_path . '/js/app', '/.*\.js$/', array('key' => 'name'));
  ksort($js);
  foreach ($js as $file_js) {
    drupal_add_js($file_js->uri, array('type' => 'file', 'scope' => 'footer'));
  }

  obiba_main_app_angular_load_external_app_js();
  global $user;
  // Add CSRF token required by restWS.
  $js_settings = array(
    'angularjsApp' => array(
      'modules' => obiba_main_app_angular_load_ng_module(),
      //  'restws_csrf_token' => drupal_get_token('restws'),
      'user' => $user
    )
  );

  drupal_add_js($js_settings, 'setting');
}

function obiba_main_app_angular_main_page() {
  obiba_main_app_angular_load_js_resources();
  return theme('obiba_angular_main');
}

function obiba_main_app_angular_get_angular_template($module, $angular_template) {
  print theme($angular_template);
}

/**
 * Implement hook_Library
 *
 */
function obiba_main_app_angular_load_angular_library() {
  $libraries = array();
  $lib_path_schema_form = libraries_get_path('angular-app');
  // Make sure we have a valid library path before returning library load info.
  if (!empty($lib_path_schema_form)) {
    $libraries['angular-app'] = array(
      'title' => 'Angular Js + dependencies',
      'website' => 'https://angularjs.org',
      'version' => 'Last Version',
      'js' => array(

        $lib_path_schema_form . '/angular/angular.min.js' => array('type' => 'file', 'scope' => 'footer'),
        $lib_path_schema_form . '/angular-resource/angular-resource.min.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/angular-bootstrap/ui-bootstrap-tpls.min.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/angular-sanitize/angular-sanitize.min.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/tv4/tv4.js' => array('type' => 'file', 'scope' => 'footer'),
        $lib_path_schema_form . '/objectpath/lib/ObjectPath.js' => array('type' => 'file', 'scope' => 'footer'),
        $lib_path_schema_form . '/angular-schema-form/dist/schema-form.min.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/angular-schema-form/dist/bootstrap-decorator.min.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/angular-route/angular-route.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/angular-translate/angular-translate.min.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/angular-marked/angular-marked.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/angular-moment/angular-moment.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/ng-obiba/dist/ng-obiba.min.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/angular-recaptcha/release/angular-recaptcha.min.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/angular-utils-pagination/dirPagination.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
      ),
//      'css' => array(
//        $lib_path_schema_form . '/extensions/FixedColumns/css/dataTables.fixedColumns.css' => array()
//      )
    );
  }
  return $libraries;
}

function obiba_main_app_angular_load_libraires_resources($module_name) {
  if (drupal_get_library($module_name, 'angular-app')) {
    drupal_add_library($module_name, 'angular-app');
  }
  else {
    watchdog($module_name, 'The library angular-app not loaded', array(), WATCHDOG_WARNING);
  }
}
