<?php
/*
 * Copyright (c) 2015 OBiBa. All rights reserved.
 *
 * This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

function sub_app_menu() {
  $items = array();

  $items['obiba-sub-module'] = array(
    'page callback' => 'sub_module_main_page',
    'access callback' => TRUE,
//    'page arguments' => array(2)
  );
  return $items;
}

/**
 * Implementation of hook_get_ng_module_to_load()
 */

function sub_app_get_ng_module_to_load() {
  return 'mica.subApp';
}

/**
 * Implements hook_theme().
 */
function sub_app_theme($existing, $type, $theme, $path) {
  $path_theme = $path . '/js/views';
  //load external AngularJs app to implement their template folder
  $templates['sub_app_ng_template_controller'] = array(
    'template' => 'sub_app_ng_template_controller',
    'path' => $path_theme,
  );

  return $templates;
}

/**
 * Implementation of hook_get_js()
 */
function sub_app_get_js() {
//  /obiba_main_app_angular_load_libraires_resources('sub_app');
  $module_path = drupal_get_path('module', 'sub_app');
  $js = file_scan_directory($module_path . '/js', '/.*\.js$/', array('key' => 'name'));
  ksort($js);
  foreach ($js as $file_js) {
    drupal_add_js($file_js->uri, array('type' => 'file', 'scope' => 'footer'));
  }
}

function sub_module_main_page() {
  return 'hello Word';
}