<?php

/**
 * @file
 * Code for obiba_mica_commons module.
 */

const HEADER_BINARY = 'application/x-protobuf';
const HEADER_JSON = 'application/json';

/**
 * Implements hook_user_logout().
 */
function obiba_mica_commons_user_logout() {
  $mica_client = new MicaClient();
  $mica_client->logout();
}

/**
 * Implements hook_user_login().
 */
function obiba_mica_commons_user_login() {
  MicaClient::clear();
}

/**
 * Implements hook_menu().
 */
function obiba_mica_commons_menu() {
  $items = array();

  $items['mica/get_fixed_sidebar/%'] = array(
    'page callback' => 'obiba_mica_commons_fixed_sidebar',
    'access callback' => TRUE,
    'page arguments' => array(2),
  );

  $items['mica/datatable-international'] = array(
    'title' => 'Dataset',
    'page callback' => 'obiba_mica_commons_datatables_multi_Lang',
    'access callback' => TRUE,
    'page arguments' => array(),
  );

  return $items;
}

/**
 * Implements hook_library_alter().
 */
function obiba_mica_commons_library_alter(&$libraries, $module) {

  $charts_info = variable_get('charts_default_settings');

  $mica_common_chart_js = drupal_get_path('module', 'obiba_mica_commons');
  if (!empty($libraries['charts_google']) && $charts_info['library'] == 'google') {
    foreach ($libraries['charts_google']['js'] as $key => $js) {
      if (strpos($js['data'], 'charts_google')) {
        $libraries['charts_google']['js'][$key]['data'] = $mica_common_chart_js . '/js/charts_google.js';
      }
    }
  }
  elseif (!empty($libraries['charts_highcharts']) && $charts_info['library'] == 'highcharts') {
    foreach ($libraries['charts_highcharts']['js'] as $key => $js) {
      if (strpos($js['data'], 'charts_highcharts')) {
        $libraries['charts_highcharts']['js'][$key]['data'] = $mica_common_chart_js . '/js/charts_highcharts.js';
      }
    }
  }
  else {
    $libraries['charts_google']['title'] = 'Google Charts integration';
    $libraries['charts_google']['version'] = '1.0';
    $libraries['charts_google']['js'][0]['data'] = NULL;
    $libraries['charts_google']['js'][0]['type'] = 'file | (Callback) file();';
    $libraries['charts_google']['dependencies'][0][0] = 'charts_google';
    $libraries['charts_google']['dependencies'][0][1] = 'visualization';
    drupal_add_js($mica_common_chart_js . '/js/charts_google.js', 'file');
  }
}

/**
 * Construct the fixed sidebar.
 *
 * @param string $template
 *   The template to render the fixed sidebar.
 */
function obiba_mica_commons_fixed_sidebar($template) {
  $output['fixed_menu'] = theme($template, $_SESSION['fixed_menu']);
  drupal_json_output($output);
}

/**
 * Get localized field value from response server.
 *
 * @param object $std
 *   The object with localized fields.
 * @param string $field
 *   The localized field to translate.
 * @param string $lang
 *   The language translations.
 *
 * @return string
 *   The localized value for this field, with this priority order: $lang,
 *   $language->language, 'en' or the first other locale found.
 */
function obiba_mica_commons_get_localized_field($std, $field, $lang = NULL) {
  global $language;
  if (empty($lang)) {
    $lang = $language->language;
  }
  $value = NULL;
  if (!empty($std->{$field})) {
    foreach ($std->{$field} as $field_value) {
      if (!empty($lang) && $lang == $field_value->lang) {
        return $field_value->value;
      }
      elseif ($field_value->lang == 'en') {
        $value = $field_value->value;
      }
      else {
        $value = $field_value->value;
      }
    }
  }
  elseif (is_array($std) && !empty($std[$field])) {
    foreach ($std[$field] as $field_value) {
      if (!empty($lang) && $lang == $field_value['lang']) {
        return $field_value['value'];
      }
      elseif ($field_value['lang'] == 'en') {
        $value = $field_value['value'];
      }
      else {
        $value = $field_value['value'];
      }
    }
  }
  return $value;
}

/**
 * Multi language Datatables  support.
 */
function obiba_mica_commons_datatables_multi_Lang() {
  drupal_json_output(array(
    "sEmptyTable" => t("No data available in table"),
    "sInfo" => t("Showing @start to @end of @total entries", array(
      "@start" => "_START_",
      "@end" => "_END_",
      "@total" => "_TOTAL_",
    )),
    "sInfoEmpty" => t("Showing 0 to 0 of 0 entries"),
    "sInfoFiltered" => t("(filtered from @max total entries)", array("@max" => "_MAX_")),
    "sInfoPostFix" => '',
    "sInfoThousands" => t(","),
    "sLengthMenu" => t("Show @menu entries", array("@menu" => "_MENU_")),
    "sLoadingRecords" => t("Loading..."),
    "sProcessing" => t("Processing..."),
    "sSearch" => t("Search :"),
    "sZeroRecords" => t("No matching records found"),
    "oPaginate" => array(
      "sFirst" => t("First"),
      "sLast" => t("Last"),
      "sNext" => t("Next"),
      "sPrevious" => t("Previous"),
    ),
    "oAria" => array(
      "sSortAscending" => t(": activate to sort column ascending"),
      "sSortDescending" => t(": activate to sort column descending"),
    ),
  ));
}

/**
 * Add external js dataTables.
 */
function obiba_mica_commons_datatables_external_source() {
  drupal_add_js('http://cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js', 'external');
  drupal_add_js('http://cdn.datatables.net/fixedcolumns/3.0.2/js/dataTables.fixedColumns.min.js', 'external');
  drupal_add_js('http://cdn.datatables.net/plug-ins/9dcbecd42ad/integration/bootstrap/3/dataTables.bootstrap.js', 'external');
  drupal_add_css('http://cdn.datatables.net/plug-ins/9dcbecd42ad/integration/bootstrap/3/dataTables.bootstrap.css', 'external');
}

/**
 * Change a keyword into a readable string.
 *
 * @param string $str
 *   A given string to clear.
 *
 * @return string
 *   A clear string.
 */
function obiba_mica_commons_clean_string($str) {
  if (empty($str)) {
    return $str;
  }
  if (is_array($str)) {
    $nstr = array();
    foreach ($str as $k => $v) {
      $nstr[$k] = t(obiba_mica_commons_clean_string($v));
    }
    return $nstr;
  }

  return t(str_replace('_', ' ', $str));
}

/**
 * Get localized dto field.
 *
 * @param object $std
 *   The object with localized fields.
 * @param string $field
 *   The localized field.
 *
 * @return string
 *   The localized value for this field, with this priority order: $lang,
 *   $language->language, 'en' or the first other locale found.
 */
function obiba_mica_commons_get_localized_dtos_field($std, $field) {
  $value = array();
  foreach ($std->{$field} as $items) {
    $value[] = obiba_mica_commons_get_localized_field($items, 'localizedStrings');
  }
  return $value;
}

/**
 * Wrap no limit value to literal output.
 *
 * @param bool $limit
 *   False/True field.
 *
 * @return string
 *   Text 'no limit' if $limit is not Null.
 */
function obiba_mica_commons_get_if_no_limit($limit) {
  if (!empty($limit)) {
    return t('No limit');
  }
}

/**
 * Get name from country code.
 *
 * @param object $iso_countries
 *   The country in iso3 format.
 *
 * @return string
 *   CamelCase Country name.
 */
function obiba_mica_commons_countries($iso_countries) {
  ob_start();
  obiba_mica_commons_iterate_field($iso_countries, 'countries_country_lookup', 'iso3', 'name');
  return ob_get_clean();
}

/**
 * An iteration field helper.
 *
 * @param object $fields
 *   Fields to iterate.
 * @param string $callback
 *   Function to use on iteration.
 * @param string $parameters
 *   A set of parameters.
 * @param string $method
 *   The method to use to get field.
 */
function obiba_mica_commons_iterate_field($fields, $callback = NULL, $parameters = NULL, $method = NULL) {
  $i = 0;
  $total_item = count($fields);
  foreach ($fields as $field) {
    if (!empty($callback)) {
      if (empty($parameters)) {
        print call_user_func($callback, $field);
      }
      elseif (empty($method)) {
        print call_user_func_array($callback, array($field, $parameters));
      }
      else {
        try {
          $user_func = call_user_func_array($callback, array(
            $field,
            $parameters,
          ));
          if (!empty($user_func->{$method})) {
            print t($user_func->{$method});
          }
          else {
            print $field;
          }
        }
        catch (Exception $e) {
          /*dpm($e->getMessage());
          dpm($callback);
          dpm($field);
          dpm($parameters);
          dpm($method);*/
          print $field;
        }
      }

    }
    else {
      print obiba_mica_commons_clean_string($field);
    }
    if ($i + 1 < $total_item) {
      print ', ';
    }
    $i++;
  }

}

/**
 * Normalize date start/end in dce.
 *
 * @param array $dce_rows
 *   The set of given dce.
 */
function obiba_mica_commons_normalize_rows(&$dce_rows) {
  foreach ($dce_rows as &$dce_row) {
    $dce_row['data']['start'] = obiba_mica_commons_format_year($dce_row['data']['start_year'], $dce_row['data']['start_month']);
    $dce_row['data']['end'] = obiba_mica_commons_format_year($dce_row['data']['end_year'], $dce_row['data']['end_month']);
    unset($dce_row['data']['start_year']);
    unset($dce_row['data']['start_month']);
    unset($dce_row['data']['end_year']);
    unset($dce_row['data']['end_month']);
    unset($dce_row['data']['created']);
  }
}

/**
 * GEt month name for a given date.
 *
 * @param int $month
 *   Number format of month.
 *
 * @return string
 *   Literal format of a month.
 */
function obiba_mica_commons_get_month_name($month) {
  global $language;
  return format_date(mktime(0, 0, 0, $month, 1, 2013), 'custom', 'F', NULL, $language->language);
}

/**
 * Get number of month in given number of year.
 *
 * @param int $year
 *   Number of years.
 * @param int $month
 *   Number of month.
 *
 * @return int
 *   period on month number.
 */
function obiba_mica_commons_convert_to_month($year, $month) {
  return $year * 12 + $month;
}

/**
 * Format year.
 *
 * @param int $year
 *   the year date.
 * @param int $month
 *   The month date.
 *
 * @return string
 *   Literal format of a given date.
 */
function obiba_mica_commons_format_year($year, $month) {
  if (empty($year)) {
    return '';
  }
  return empty($month) ? "$year" : "$year (" . obiba_mica_commons_get_month_name($month) . ")";
}

/**
 * Helper to add page node.
 *
 * @param string $title
 *   The title of the page.
 * @param string $body_html
 *   The content body of the page.
 * @param string $alias
 *   The alias path of the page.
 * @param string $format
 *   Format of the body content.
 *
 * @return object
 *   The created entity wrapper of the created page.
 */
function obiba_mica_commons_add_page($title, $body_html, $alias = NULL, $format = 'full_html') {

  $page_wrapper = entity_property_values_create_entity(
    'node',
    array(
      'type' => 'page',
      'title' => $title,
      'title_field' => $title,
      'body' => array(
        'value' => $body_html,
        'format' => $format,
      ),
      'language' => LANGUAGE_NONE,
      'comment' => COMMENT_NODE_CLOSED,
    )
  )->save();

  if (isset($alias)) {
    $path = array('alias' => $alias);
    $path['source'] = 'node/' . $page_wrapper->getIdentifier();
    $path['language'] = LANGUAGE_NONE;
    path_save($path);
  }

  return $page_wrapper->value();
}

/**
 * Get the current theme name.
 *
 * @return string
 *   The current theme name.
 */
function obiba_mica_commons_get_current_theme() {
  global $theme, $user;
  if (!empty($user->theme)) {
    return $user->theme;
  }
  return $theme ? $theme : 'obiba_bootstrap';
}

/**
 * Create a search form in list pages (Study list, network list...).
 *
 * @param array $context
 *   An array of options and context.
 * @param bool $no_acronym
 *   Sorting by acronym options.
 * @param bool $no_name
 *   Sorting by name options
 *
 * @return array
 *   Drupal markup form.
 */
function obiba_mica_commons_create_search_form($context, $no_acronym = TRUE, $no_name = TRUE) {
  global $language;
  if ($no_name) {
    $sort_name = 'name.' . $language->language;
  }
  if ($no_acronym) {
    $sort_acronym = 'acronym.' . $language->language;
    $options = array_merge(array(
      $sort_name => t('Name'),
      $sort_acronym => t('Acronym'),
    ), $context['options']);
  }
  else {
    $options = array_merge(array($sort_name => t('Name')), $context['options']);
  }

  $default_sort = empty($_GET['search-sort']) ?
    empty($context['default_sort']) ? NULL : $context['default_sort'] :
    $_GET['search-sort'];

  $default_sort_order = empty($_GET['search-sort-order']) ?
    empty($context['default_sort_order']) ? NULL :
      $context['default_sort_order'] : $_GET['search-sort-order'];

  $form = array();
  $form['#id'] = 'obiba-mica-search-form';
  $form['#method'] = 'get';
  $form['#attributes'] = array(
    'class' => 'form-inline',
  );
  if (isset($_GET['search-sort']) ||
    isset($_GET['search-sort-order']) ||
    isset($_GET['search-query'])
  ) {
    $form['button'] = array(
      '#type' => 'button',
      '#value' => '<i class="flaticon-undo9"></i>',
      '#attributes' => array(
        'class' => array('btn-default rounded'),
        'id' => array('refresh-button'),
      ),
    );
  }

  $form['search-sort'] = array(
    '#type' => 'select',
    '#theme_wrappers' => array(), // remove the wrapper
    '#title' => '',
    '#description' => t('Sort by'),
    '#options' => $options,
    '#default_value' => $default_sort,
  );

  $form['search-sort-order'] = array(
    '#type' => 'select',
    '#theme_wrappers' => array(), // remove the wrapper
    '#title' => '',
    '#description' => t('Sort order'),
    '#options' => array(
      'asc' => t('Asc.'),
      'desc' => t('Desc.'),
    ),
    '#default_value' => $default_sort_order,
  );

  $form['search-query'] = array(
    '#type' => 'textfield',
    '#title' => '',
    '#size' => 15,
    '#description' => t('Filter by'),
    '#theme_wrappers' => array(), // remove the wrapper
    '#default_value' => !empty($_GET['search-query']) ? check_plain($_GET['search-query']) : NULL,
    '#prefix' => '<div class="input-group"><span class="input-group-addon glyphicon glyphicon-search"></span>',
    '#suffix' => '</div>',
  );

  return $form;
}

/**
 * Create a size select form.
 *
 * @param array $context
 *   An array of options and context.
 *
 * @return array
 *   Drupal markup form.
 */
function obiba_mica_commons_create_size_select_form($context) {
  $default_size_parameter = MicaClient::getResponsePageSize();
  $default_size = !empty($default_size_parameter) ?
    $default_size_parameter : $context['options'];
  $form = array();
  $form['#id'] = 'obiba-mica-size-select-form';
  $form['#method'] = 'get';

  $form['#prefix'] = $context['#prefix'] ? $context['#prefix'] : '';
  $form['#suffix'] = $context['#suffix'] ? $context['#suffix'] : '';

  $form['size'] = array(
    '#type' => 'select',
    '#title' => '',
    '#description' => t('Nbr items'),
    '#options' => $context['options'],
    '#default_value' => $default_size,
    '#prefix' => '<div class="input-group">',
    '#suffix' => "</div>",
    '#theme_wrappers' => array(), // remove the wrapper
    '#attributes' => array(
      'id' => 'edit-size',
    ),
  );

  return $form;
}

/**
 * Safe expose hosted mica server images.
 *
 * By save the image in tmp and expose an cached image resource.
 *
 * @param string $entity_id
 *   The entity id.
 * @param object $file_resource
 *   The file resource.
 * @param string $entity_type
 *   the entity type.
 * @param bool $link_to
 *   Disable/enable link to image.
 *
 * @return string
 *   The url of image.
 */
function obiba_mica_commons_safe_expose_server_url($entity_id, $file_resource, $entity_type, $link_to = FALSE) {

  if ($link_to) {
    if (!strstr(drupal_get_js(), 'fancybox')) {
      return '#';
    }
  }
  $attached_resource = &drupal_static(__FUNCTION__);
  if (!isset($attached_resource)) {
    $cached_attached_resources = cache_get('images-cache-' . $entity_id . '-' .
      $file_resource->id);

    if (!empty($cached_attached_resources)) {
      return $cached_attached_resources->data;
    }
    else {
      if (!empty($file_resource)) {
        $mica_client = new MicaClient();
        $raw_data = $mica_client->downloadFile($entity_type, $entity_id,
          $file_resource->id);
        if (!empty($raw_data) && empty($raw_data['code'])) {
          $extension_file = $raw_data['extension'];
          $file = file_unmanaged_save_data($raw_data['data'], 'public://tmp' .
            $file_resource->id . '.' . $extension_file, FILE_EXISTS_REPLACE);
          $exposed_url = file_create_url($file);
          // Time out in second.
          $time_out = variable_get_value('image_cache_time_out') * 60;
          cache_set('images-cache-' . $entity_id . '-' . $file_resource->id,
            $exposed_url, 'cache', time() + $time_out);
          return $exposed_url;
        }
        else {
          drupal_set_message(t('An error occurred downloading images , server
          response code : @code, Server message: "@message"',
            array(
              '@code' => $raw_data['code'],
              '@message' => $raw_data['message'],
            )
          ),
            'error');
          return NULL;
        }
      }
    }
  }
  return NULL;
}

/**
 * Transform a markdown text into html and wrap it in a div with markdown class.
 *
 * @param string $text
 *   Markdown format text.
 *
 * @return string
 *   Html format text.
 */
function obiba_mica_commons_markdown($text) {
  if (!empty($text)) {
    $formatter = new Parsedown();
    return '<div class="markdown">' . $formatter->text($text) . '</div>';
  }
  return $text;
}

/**
 * Check if current request is an ajax one.
 *
 * @return bool
 *   TRUE/FALSE statement.
 */
function obiba_mica_commons_is_ajax() {
  return !empty($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest';
}

/**
 * Format number by current selected page.
 *
 * @param int $number
 *   The number to format.
 * @param int $nbr_decimals
 *   The number of decimal.
 *
 * @return string
 *   The formatted number.
 */
function obiba_mica_commons_format_number($number, $nbr_decimals = 0) {
  global $language;
  switch ($language->language) {
    case 'fr':
      if (is_float($number)) {
        return number_format($number, $nbr_decimals, ',', ' ');
      }
      else {
        return $number;
      }

    default:
      if (is_float($number)) {
        return number_format($number, $nbr_decimals, '.', ',');
      }
      else {
        return $number;
      }
  }
}

/**
 * GEt translated node.
 *
 * @param int $nid
 *   The id of the node.
 *
 * @return array
 *   The node on an drupal markup array.
 */
function obiba_mica_commons_get_translated_node($nid) {
  $loaded_node = (node_load($nid));
  if (!empty($loaded_node)) {
    if (module_exists('locale') && module_exists('translation')) {
      global $language;
      $translations = translation_node_get_translations($nid);
      if (!empty($translations)) {
        $loaded_node = (node_load($translations[$language->language]->nid));
      }
    }
    $node_rendered = node_view($loaded_node);
    return $node_rendered;
  }
  return FALSE;
}

/**
 * Helper to check if current user is an authorized Agete user.
 *
 * @return bool
 *   TRUE/FALSE statment.
 */
function obiba_mica_commons_is_authorized_agate_user() {
  global $user;

  if (!empty($user->session) && strstr($user->session, 'obibaid')) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Helper return the taxonomies filter on an array format
 */
function obiba_mica_commons_taxonomies_filter_array() {
  $mica_taxonomy_figures = trim(variable_get_value('mica_taxonomy_figures'));
  if (empty($mica_taxonomy_figures)) {
    return NULL;
  }
  return explode(',', $mica_taxonomy_figures);
}

/**
 * Helper to set cache for current user
 */
function obiba_mica_commons_set_cache($key, $value) {
  if (variable_get_value('cache') == 1) {
    $key = md5($key);
    global $user;
    if (in_array('anonymous user', $user->roles, TRUE)) {
      cache_set($key . '-' . 'anonymous_user', $value, 'cache', MicaClient::ANONYMOUS_CACHE_LIFE_TIME);
    }
    else {
      cache_set($key . '-' . $user->sid, $value, 'cache', MicaClient::AUTHENTICATED_CACHE_LIFE_TIME);
    }
  }
}

/**
 * Helper to get cache for current user
 */
function obiba_mica_commons_get_cache($key) {
  if (variable_get_value('cache') == 1) {
    $key = md5($key);
    global $user;
    if (in_array('anonymous user', $user->roles, TRUE)) {
      return cache_get($key . '-' . 'anonymous_user');
    }
    else {
      return cache_get($key . '-' . $user->sid);
    }
  }
  return FALSE;
}
