<?php
/**
 * Copyright (c) 2018 OBiBa. All rights reserved.
 *
 * This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * @file code for obiba_mica_analysis module
 */
function obiba_mica_analysis_menu() {
  $items = array();
  $items[ObibaAnalysisResources::MICA_ANALYSIS . '/entities_count/ws'] = array(
    'page callback' => 'obiba_mica_analysis_entities_count_query',
    'file' => 'obiba_mica_analysis_services.inc',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_get_js().
 */
function obiba_mica_analysis_get_js($weight_js) {
  if (current_path() == MicaClientPathProvider::ANALYSIS) {
    $module_path = drupal_get_path('module', 'obiba_mica_analysis');
    $js = file_scan_directory($module_path . '/js/app', '/.*\.js$/', array('key' => 'name'));
    ksort($js);
    foreach ($js as $file_js) {
      drupal_add_js($file_js->uri, array(
        'type' => 'file',
        'scope' => 'footer',
        'weight' => ++$weight_js,
      ));
    }
  }
  return ++$weight_js;
}

/**
 * Implements hook_load_menus().
 */
function obiba_mica_analysis_load_menus() {
  $items = array();

  $items[MicaClientPathProvider::ANALYSIS] = array(
    'access callback' => TRUE,
    'title' => variable_get('entities_count_page_title', 'Entities Count'),
    'module_caller' => 'obiba_mica_analysis',
    'type' => MENU_CALLBACK,
    'options' => array('fragment' => 'entities-count'),
  );
  return $items;
}

/**
 * Implements hook_get_ng_module_to_load().
 */
function obiba_mica_analysis_get_ng_module_to_load() {
  if (current_path() == MicaClientPathProvider::ANALYSIS) {
    return 'mica.ObibaAnalysis';
  }
  return FALSE;
}

/**
 * Implements hook_theme().
 */
function obiba_mica_analysis_theme($existing, $type, $theme, $path) {
  $path_template = $path . '/templates';
  $path_views = $path . '/js/app/views';
  return array(
    'obiba_mica_analysis_main_app' => array(
      'template' => 'obiba_mica_analysis_main_app',
      'path' => $path_template,
    ),
    'obiba_mica_analysis_entities_count-view-header' => array(
      'template' => 'obiba_mica_analysis_entities_count-view-header',
      'path' => $path_views,
    ),
  );

}

/**
 * Main Analysis page
 */
function obiba_mica_analysis_variable_page_search() {
  return theme('obiba_mica_analysis_main_app', array());
}
