<?php
/**
 * @file
 * Mica studies file
 */

function mica_population_page_detail($population_id)
{
//    $page_render_study = NULL;
//    $query = new QueryDto();
//    $param = 'study/' . $study_id;
//    $StudyDto = $query->get_detail($param, '\obiba\mica\StudyDto');
//  //  dpm($StudyDto);
//    drupal_set_title(mica_commons_get_localized_field($StudyDto, 'name'));
//    $output['data'] = $StudyDto;
//    foreach ($StudyDto->populations as $population) {dpm($population);
//        $page_render_study .= theme('mica_population_detail', array());
//    }
//    dpm($page_render_study);
//    return $page_render_study;
//  //  return theme('mica_study_detail', array("context_detail" => $output));
}
