<?php
/**
 * @file
 * Mica studies file
 */
require_once(drupal_get_path('module', 'mica_client_protos') . '/mica_client_protos-queryDto.inc');
function mica_study_menu()
{
    $items = array();
    $items['mica/studies'] = array(
        'title' => t('Mica studies'),
        'description' => t('Mica studies'),
        'page callback' => 'mica_study_page_list',
        'file' => 'mica_study-page-list.inc',
        'access callback' => TRUE,
        'menu_name' => 'main-menu',
        'type' => MENU_NORMAL_ITEM
    );
    $items['mica/study/%'] = array(
        'title' => t('Mica study detail'),
        'page callback' => 'mica_study_page_detail',
        'file' => 'mica_study-page-detail.inc',
        'access callback' => TRUE,
        'page arguments' => array(3),
    );
    return $items;
}

/**
 * Implements hook_requirements().
 */

function mica_study_requirements($phase) {
    $requirements = array();
    // Ensure translations do not break at install time
    $t = get_t();
    $requirements['micatimelines'] = array(
        'title' => $t('Time lines  Library'),
    );
    $libraries = libraries_get_libraries();
    if (isset($libraries['micatimelines'])) {
        $requirements['micatimelines']['value'] = $t('Installed');
        $requirements['micatimelines']['severity'] = REQUIREMENT_OK;
    }
    else {
        $requirements['micatimelines']['value'] = $t('Not Installed');
        $requirements['micatimelines']['severity'] = REQUIREMENT_ERROR;
        $requirements['micatimelines']['description'] = $t('Please install the the time lines library %url.', array('%url' => 'http://obiba.org.com'));
    }

    return $requirements;
}

/**
 * Implements hook_theme().
 */
function mica_study_theme($existing, $type, $theme, $path)
{
    return array(
        'mica_study_list' => array('template' => '/mica_study-list'),
        'mica_study_detail' => array('template' => '/mica_study-detail'),
        'mica_population_detail' => array('template' => '/mica_population-detail'),
    );
}
