<?php
/**
 * @file
 * Mica studies file
 */
require_once(drupal_get_path('module', 'mica_protobuf') . '/mica_protobuf-queryDto.inc');

function mica_study_menu() {
  $items = array();
  $items['mica/studies'] = array(
    'title' => t('Mica studies'),
    'description' => t('Mica studies'),
    'page callback' => 'mica_study_page_list',
    'file' => 'mica_study-page-list.inc',
    'access callback' => TRUE,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM
  );
  $items['mica/study/%'] = array(
    'title' => t('Mica study detail'),
    'page callback' => 'mica_study_page_detail',
    'file' => 'mica_study-page-detail.inc',
    'access callback' => TRUE,
    'page arguments' => array(3),
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function mica_study_theme($existing, $type, $theme, $path) {
  return array(
    'mica_study_list' => array('template' => '/mica_study-list'),
    'mica_study_detail' => array('template' => '/mica_study-detail'),
  );
}
