<?php

/**
 * @file
 * Code for the obiba_mica modules.
 */

/**
 * Implements hook_menu().
 */
function obiba_mica_menu() {
  global $user;
  $items = array();

  $items['admin/config/system/obiba'] = array(
    'title' => 'OBiBa Mica settings',
    'description' => 'Configure Mica services',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('obiba_mica_admin_settings'),
    'access arguments' => array('administer obiba'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'obiba_mica.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_theme_registry_alter().
 */
function obiba_mica_theme_registry_alter(&$theme_registry) {
  $themes_to_override = array();
  $module_template_override = NULL;

  foreach (module_implements('mica_override_templates') as $module) {
    $function = $module . '_mica_override_templates';
    $function($themes_to_override);

    if (!empty($themes_to_override)) {
      foreach ($themes_to_override as $registry_key_template => $template) {
        $module_path = drupal_get_path('module', $module);
        $theme_study_detail = array(
          'template' => $template,
          'path' => $module_path . '/templates',
          'theme path' => $module_path
        );
        $result = array_merge($theme_registry[$registry_key_template], $theme_study_detail);
        $theme_registry[$registry_key_template] = $result;
      }
    }

  }
}

function obiba_mica_user_view($account, $view_mode, $langcode) {
  // Set the page title of the user profile page to the user's full name.
  $wrapper = entity_metadata_wrapper('user', $account);
  try {
    $user_name = $wrapper->field_contact_name->value();
    if ($user_name) {
      drupal_set_title($user_name);
    }
  }
  catch (Exception $e) {

  }

}