<?php

class ObibaDatasetConstants {
  const FACET_TYPE_HIDE = 0;
  const FACET_TYPE_AUTOCOMPLETE = 1;
  const FACET_TYPE_CHECKBOX = 2;

  const  UNDETERMINED_HARMO_ICON = 'glyphicon-question-sign';
  const  COMPLETE_HARMO_ICON = 'glyphicon-ok';
  const  INCOMPLETE_HARMO_ICON = 'glyphicon-minus';
  const  IMPOSSIBLE_HARMO_ICON = 'glyphicon-remove';
}
class ObibaFacetSearchBlockConstants {
  const EXPAND_GROUPS = 'expand_groups';
  const EXPAND_ALL = 'expand_all';
}