<?php

/**
 * @file
 * Code for the obiba_mica modules.
 */

/**
 * Implements hook_menu().
 */
function obiba_mica_menu() {
  global $user;
  $items = array();

  $items['admin/config/system/obiba'] = array(
    'title' => 'OBiBa Mica settings',
    'description' => 'Configure Mica services',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('obiba_mica_admin_settings'),
    'access arguments' => array('administer obiba'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'obiba_mica.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_theme_registry_alter().
 */
function obiba_mica_theme_registry_alter(&$theme_registry) {
  $themes_to_override = array();
  $module_template_override = NULL;

  foreach (module_implements('mica_override_templates') as $module) {
    $function = $module . '_mica_override_templates';
    $function($themes_to_override);

    if (!empty($themes_to_override)) {
      foreach ($themes_to_override as $registry_key_template => $template) {
        $module_path = drupal_get_path('module', $module);
        $theme_study_detail = array(
          'template' => $template,
          'path' => $module_path . '/templates',
          'theme path' => $module_path
        );
        $result = array_merge($theme_registry[$registry_key_template], $theme_study_detail);
        $theme_registry[$registry_key_template] = $result;
      }
    }

  }
}

/**
 * Implements hook_chart_definition_alter().
 */
function obiba_mica_chart_definition_alter(&$definition, $chart, $chart_id) {
  if (!empty($chart['#raw_options'])) {
    $definition = obiba_mica_drupal_array_merge_deep_array(array($definition, array('options' => $chart['#raw_options'])));
  }
}

/**
 *
 */
function obiba_mica_load_angular_library() {
  $libraries = array();
  $lib_path_schema_form = libraries_get_path('angular-schema-form');
  // Make sure we have a valid library path before returning library load info.
  if (!empty($lib_path_schema_form)) {
    $libraries['angular-schema-form'] = array(
      'title' => 'Angular Schema Form',
      'website' => 'http://schemaform.io',
      'version' => 'Last Version',
      'js' => array(

        $lib_path_schema_form . '/angular/angular.min.js' => array('type' => 'file', 'scope' => 'footer'),
        $lib_path_schema_form . '/angular-resource/angular-resource.min.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/angular-bootstrap/ui-bootstrap-tpls.min.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/angular-sanitize/angular-sanitize.min.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/tv4/tv4.js' => array('type' => 'file', 'scope' => 'footer'),
        $lib_path_schema_form . '/objectpath/lib/ObjectPath.js' => array('type' => 'file', 'scope' => 'footer'),
        $lib_path_schema_form . '/angular-schema-form/dist/schema-form.min.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/angular-schema-form/dist/bootstrap-decorator.min.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/angular-route/angular-route.min.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/angular-translate/angular-translate.min.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/ng-obiba/dist/ng-obiba.min.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/angular-recaptcha/release/angular-recaptcha.min.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
        $lib_path_schema_form . '/angular-utils-pagination/dirPagination.js' => array(
          'type' => 'file',
          'scope' => 'footer'
        ),
      ),
//      'css' => array(
//        $lib_path_schema_form . '/extensions/FixedColumns/css/dataTables.fixedColumns.css' => array()
//      )
    );
  }
  return $libraries;
}

function obiba_mica_load_libraires_resources($module_name) {
  if (drupal_get_library($module_name, 'angular-schema-form')) {
    drupal_add_library($module_name, 'angular-schema-form');
  }
  else {
    watchdog($module_name, 'The library angular-schema-form not loaded', array(), WATCHDOG_WARNING);
  }
}

/**
 * Override drupal_array_merge_deep_array
 *
 * @param $arrays
 *
 * @return array
 */
function obiba_mica_drupal_array_merge_deep_array($arrays) {
  $result = array();

  foreach ($arrays as $array) {
    foreach ($array as $key => $value) {
      // Renumber integer keys as array_merge_recursive() does. Note that PHP
      // automatically converts array keys that are integer strings (e.g., '1')
      // to integers.
      if (isset($result[$key]) && is_array($result[$key]) && is_array($value)) {
        $result[$key] = obiba_mica_drupal_array_merge_deep_array(array($result[$key], $value));
      }
      // Otherwise, use the latter value, overriding any previous value.
      else {
        $result[$key] = $value;
      }
    }
  }

  return $result;
}

function obiba_mica_user_view($account, $view_mode, $langcode) {
  // Set the page title of the user profile page to the user's full name.
  $wrapper = entity_metadata_wrapper('user', $account);
  try {
    $user_name = $wrapper->field_contact_name->value();
    if ($user_name) {
      drupal_set_title($user_name);
    }
  } catch (Exception $e) {

  }

}

/**
 * Adds the obiba progressbar JS file
 * @param $javascript
 */
function obiba_mica_js_alter(&$javascript) {
  $js_file = _get_progressbar_path('.js');
  if (!empty($js_file)) {
    $javascript[$js_file] = drupal_js_defaults($js_file);
  }
}

/**
 * Adds the obiba progressbar reltated CSS file
 * @param $javascript
 */
function obiba_mica_css_alter(&$css) {
  $css_file = _get_progressbar_path('.css');
  if (!empty($css_file)) {
    $css = drupal_add_css($css_file, array('every_page' => TRUE));
  }
}

/**
 * Helper assembling the resource files setup in the Makefile
 * @param $extension
 * @return null|string
 */
function _get_progressbar_path($extension) {
  $obiba_progressbar_lib = libraries_get_path(variable_get_value('obiba-progressbar-lib'));
  $obiba_progressbar_file = variable_get_value('obiba-progressbar-file');
  return empty($extension) || empty($obiba_progressbar_lib) || empty($obiba_progressbar_file)
    ? NULL
    : $obiba_progressbar_lib . '/' . $obiba_progressbar_file . $extension;
}

/**
 * Increase the length of the slogan.
 * Implements hook_form_FORM_ID_alter.
 */
function obiba_mica_form_system_site_information_settings_alter(&$form, &$form_state, $form_id) {
  $form['site_information']['site_slogan']['#maxlength'] = 500;
}
