<?php
/*
 * @file code for obiba_mica_search module
 * */
$path_module_protobuf = drupal_get_path('module', 'obiba_mica_study');
include_once($path_module_protobuf . '/obiba_mica_study-page-list.inc');

include_once('includes/obiba_mica_search_resource.inc');
include_once('includes/obiba_mica_search_resource_facet_conf.inc');
include_once('obiba_mica_search_charts.php');

function obiba_mica_search_menu() {
  $items = array();

  $items['mica/search'] = array(
    'title' => 'Search',
    'description' => 'Search',
    'page callback' => 'obiba_mica_search_variable_page_search',
    'menu_name' => 'main-menu',
    'weight' => 10,
    'access callback' => TRUE
  );

  $items['mica/coverage'] = array(
    'title' => 'Classification',
    'description' => 'Variable Classification',
    'page callback' => 'obiba_mica_search_coverage_page',
    'menu_name' => 'main-menu',
    'weight' => 11,
    'access callback' => TRUE
  );

  $items['mica/coverage/download'] = array(
    'page callback' => 'obiba_mica_search_coverage_download',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );

  $items['mica/studies_search/%'] = array(
    'title' => 'Studies Search',
    'description' => 'Search published studies',
    'page callback' => 'obiba_mica_search_study_page_search',
    'access callback' => TRUE,
    'page arguments' => array(2)
  );

  $items['bucket/autocomplete/%'] = array(
    'page callback' => 'obiba_mica_search_autocomplete_ajax_response',
    'file' => 'includes/obiba_mica_search_resource_facet_conf.inc',
    'access callback' => TRUE,
    'page arguments' => array(2),
    'type' => MENU_CALLBACK
  );

  return $items;
}

/**
 * Implements hook_theme().
 *
 * copy '<modules>/obiba_mica_dataset/templates/'   files in  your customized theme  '<YOUR_THEME>/templates/' path
 * you can modify default display of listed page templates by rearrange block field for example
 * don't forget to clear the theme registry.
 *
 */

function obiba_mica_search_theme($existing, $type, $theme, $path) {
  $path_theme = $path . '/templates';
  return array(
    'block__obiba_mica_search' => array(
      'variables' => array('block' => array()),
      'template' => 'block--obiba_mica_search',
      'path' => $path_theme
    ),
    'obiba_mica_search_block_search' => array(
      'template' => 'obiba_mica_search_block_search',
      'path' => $path_theme
    ),
    'obiba_mica_search_search' => array(
      'template' => 'obiba_mica_search_search',
      'path' => $path_theme
    ),
    'obiba_mica_search_coverage' => array(
      'template' => 'obiba_mica_search_coverage',
      'path' => $path_theme
    ),
    'obiba_mica_search_coverage_taxonomy' => array(
      'template' => 'obiba_mica_search_coverage_taxonomy',
      'path' => $path_theme
    ),
    'obiba_mica_search_vocabulary_coverage' => array(
      'template' => 'obiba_mica_search_vocabulary_coverage',
      'path' => $path_theme
    ),
    'obiba_mica_search_checkbox_term' => array(
      'template' => 'obiba_mica_search_checkbox_term',
      'path' => $path_theme
    ),
    'obiba_mica_search_input_text_range' => array(
      'template' => 'obiba_mica_search_input_text_range',
      'path' => $path_theme
    ),
    'obiba_mica_search_tab_block' => array(
      'template' => 'obiba_mica_search_tab_block',
      'path' => $path_theme
    ),
    'obiba_mica_search_charts' => array(
      'template' => 'obiba_mica_search_charts',
      'path' => $path_theme
    ),
    'obiba_mica_search_vocabulary_charts' => array(
      'template' => 'obiba_mica_search_vocabulary_charts',
      'path' => $path_theme
    ),
    'obiba_mica_search_fixed_sidebar' => array(
      'template' => 'obiba_mica_search_fixed_sidebar',
      'path' => $path_theme
    ),
    'obiba_mica_search_cloned_block' => array(
      'template' => 'obiba_mica_search_cloned_block',
      'path' => $path_theme
    ),
    'obiba_mica_search_aggregation_group' => array(
      'template' => 'obiba_mica_search_aggregation_group',
      'path' => $path_theme
    )
  );
}

function obiba_mica_commons_create_full_text_query_form($arg) {
  $args = func_get_args();
  $type = $args[2];
  if (empty($type)) {
    throw new InvalidArgumentException("drupal_get_form() form type is missing from argument list.");
    return;
  }

  $form = array();
  $form['#id'] = 'facet-search-query-form-' . $type;
  $form['#method'] = 'get';
  $form['#prefix'] = '<div class="inline-form">';
  $form['#suffix'] = '</div>';

  $input_id = "$type:matches:facet-search-query";
  $form['facet-search-query' . $type] = array(
    '#type' => 'textfield',
    '#title' => '',
    '#description' => 'Filter by',
    '#default_value' => !empty($_GET['search-query']) ? check_plain($_GET['search-query']) : NULL,
    '#prefix' => '<div class="lg-width"><div class="input-group"><span class="input-group-addon"><i class="glyphicon glyphicon-filter"></i></span>',
    '#suffix' => "</div></div>",
    '#attributes' => array('id' => $input_id, 'name' => $input_id)
  );

  return $form;
}

/**
 * Implements hook_block_info().
 */
function obiba_mica_search_block_info() {
  $blocks['facet-search'] = array(
    'info' => t('Facet search'),
    'title' => t('Facet search'),
    'status' => 1,
    'region' => 'facets',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '*mica/search
*mica/coverage',
    'weight' => 10,
    'custom' => 1,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function obiba_mica_search_block_view($delta = '') {
  switch ($delta) {
    case 'facet-search':
      $output = _get_facets_theme();
      $block['subject'] = t('Facet search');
      $block['content'] = $output;
      return $block;
  }
}

function _get_facets_theme() {
  return theme('obiba_mica_search_tab_block', array(
    'obiba_mica_variable' =>
      _obiba_mica_search_get_facets_block_by_dto_type('facet_conf_variable', 'variables'),
    'obiba_mica_study' =>
      variable_get_value('studies_facet_search')
        ? _obiba_mica_search_get_facets_block_by_dto_type('facet_conf_study', 'studies')
        : NULL
  ));
}

function _obiba_mica_search_get_facets_block_by_dto_type($dto_type, $type) {
  $rendered_blocks = "";
  $facets = obiba_mica_search_resource_return_facets($dto_type);
  if (!empty($facets)) {
    foreach ($facets as $key_facet => $facet) {
      if (!empty($facet['children'])) {
        $rendered_group = "";

        foreach ($facet['children'] as $key_child_facet => $child_facet) {
          if (!MicaClient::has_entity_aggregations($child_facet['dto'])) {
            continue;
          }
          $content_block = obiba_mica_search_process_block_theme('search-' . $child_facet['aggs'], $type, $facet['dto']->children);
          if (!empty($content_block)) {
            $rendered_group .= theme('obiba_mica_search_cloned_block', array(
              'content' => $content_block,
              'title' => $child_facet['title'],
              'block_html_id' => $child_facet['key'],
            ));
          }
        }

        if (!empty($rendered_group)) {
          $rendered_blocks .= theme('obiba_mica_search_aggregation_group', array(
            'name' => $facet['key'],
            'title' => $facet['title'],
            'content' => $rendered_group
          ));
        }
      }
      else {
        $has_terms = MicaClient::has_entity_by_id_aggregation($facet['aggs']);
        // aggs that are from studies but must be displayed as variable aggregations
        $source_type = preg_match("/^(studyIds|dceIds)$/", $key_facet) ? "variables" : $type;
        $content_block =
          obiba_mica_search_process_block_theme(
            'search-' . $facet['aggs'],
            $type,
            $_SESSION[$source_type]['aggregations']
          );

        if (!empty($content_block)) {
          if (!empty($has_terms) || ($facet['aggs'] == 'datasetId') || ($facet['aggs'] == 'networkId')) {
            $rendered_blocks .= theme('obiba_mica_search_cloned_block', array(
              'content' => $content_block,
              'title' => $facet['title'],
              'block_html_id' => $key_facet,
            ));
          }
        }
      }
    }
  }
  return empty($rendered_blocks) ? NULL : $rendered_blocks;
}

function obiba_mica_search_load_libs() {
  $module_path_commons = drupal_get_path('module', 'obiba_mica_commons');
  drupal_add_js($module_path_commons . '/js/obiba-mica-commons-got-top.js');
  $module_path_ = drupal_get_path('module', 'obiba_mica_search');
  drupal_add_js($module_path_ . '/js/obiba-mica-search-common.js');
  drupal_add_js($module_path_ . '/js/obiba-mica-search-coverage.js');
  drupal_add_js($module_path_ . '/js/obiba-mica-search-query-serializer.js');
  drupal_add_js($module_path_ . '/js/obiba-mica-search_collapse_deal.js');
  drupal_add_js(array('expand_strategy' => _obiba_mica_search_facet_expand_strategy()), 'setting');
  drupal_add_js($module_path_ . '/js/obiba-mica-search_tab_deal.js');
  drupal_add_js($module_path_ . '/js/obiba-mica-search-href.js');
  drupal_add_js(array(
    'ShowStudiesFacets' => variable_get_value('studies_facet_search'),
    'UrlErrorsQuery' => !empty($_SESSION['errorsQuery']) ? $_SESSION['errorsQuery'] : NULL,
    'ErrorMessage' => t('An error occurred when parsing url query, Please make sure to use facet search tools
       to perform your search. <br>This page will be refeshed in 3s '),
    'ConfigTaxonomiesCount' => MicaClient::get_taxonomies_count()
  ), 'setting');
  $facet_conf["general"] = //
    array( //
      'matches' => t('matches'), //
      'match' => t('match'), //
      'is' => t('be'), //
      'and' => t('and'), //
      'or' => t('or'), //
      'variables' => t('Variables'), //
      'datasets' => t('Datasets'), //
      'studies' => t('Studies'), //
      'networks' => t('Networks') //
    );
  drupal_add_js($module_path_ . '/js/obiba-mica-search-query-renderer.js');
  drupal_add_js(array(
    'obiba_mica_facet' => array('facet_conf' => $facet_conf),
    'aggs_dictionary' => obiba_mica_search_create_aggs_dictionary()
  ), 'setting');

}

function obiba_mica_search_create_aggs_dictionary() {
  $dictionary = array();

  if (!empty($_SESSION['variables']) && !empty($_SESSION['variables']['aggregations'])) {
    $dictionary = _obiba_mica_search_create_aggs_dictionary(
      $_SESSION['variables']['aggregations'],
      function ($value) {
        return "studyIds" === $value ? "studies" : "variables";
      }
    );
  }

  if (!empty($_SESSION['studies']) && !empty($_SESSION['studies']['aggregations'])) {
    $dictionary = array_merge($dictionary, _obiba_mica_search_create_aggs_dictionary(
      $_SESSION['studies']['aggregations'],
      function ($value) {
        return "networkId" === $value ? "networks" : "studies";
      }
    ));
  }

  return $dictionary;
}

function _obiba_mica_search_create_aggs_dictionary($aggregations, $filter_callback) {
  $dictionary = array();
  if (!empty($aggregations)) {
    foreach ($aggregations as $aggregation) {
      if (empty($aggregation->aggregation)) {
        continue;
      }

      if (!empty($aggregation->children)) {
        $dictionary = array_merge($dictionary, _obiba_mica_search_create_aggs_dictionary($aggregation->children, $filter_callback));
        continue;
      }

      $type = $filter_callback($aggregation->aggregation);
      $dictionary[$aggregation->aggregation] = obiba_mica_commons_get_localized_field($aggregation, 'title');

      if (!empty($aggregation->{'obiba.mica.TermsAggregationResultDto.terms'})) {
        foreach ($aggregation->{'obiba.mica.TermsAggregationResultDto.terms'} as $term) {
          if (empty($term->title)) {
            $term->title = $term->key;
          }
          $dictionary[sprintf("$type:%s:%s", $aggregation->aggregation, $term->key)] = $term->title;
        }
      }
    }
  }

  return $dictionary;
}

/*
 * filter the url parameter and search for tab parameter to return correct resource
 * @return tab parameter if exist
 * */
function obiba_mica_search_get_url_tab_parameter() {
  $url_parm = explode('?', request_uri());
  $type = 'variables';
  if (!empty($url_parm[1])) {
    parse_str($url_parm[1], $parts);
    if (!empty($parts['type'])) {
      $type = $parts['type'];
    }
  }
  return $type;
}

function obiba_mica_get_hits_entities_variable($entity) {
  return array(
    'study_total_hits' => !empty($entity['study_total_hits']) ? $entity['study_total_hits'] : NULL,
    'study_total_count' => !empty($entity['study_total_hits']) ? $entity['study_total_hits'] : NULL,
    'variable_total_hits' => !empty($entity['variable_total_hits']) ? $entity['variable_total_hits'] : NULL,
    'variable_total_count' => !empty($entity['variable_total_count']) ? $entity['variable_total_count'] : NULL,
    'dataset_total_hits' => !empty($entity['dataset_total_hits']) ? $entity['dataset_total_hits'] : NULL,
    'dataset_total_count' => !empty($entity['dataset_total_count']) ? $entity['dataset_total_count'] : NULL,
    'network_total_hits' => !empty($entity['network_total_hits']) ? $entity['network_total_hits'] : NULL,
    'network_total_count' => !empty($entity['network_total_count']) ? $entity['network_total_count'] : NULL
  );
}

function _obiba_mica_search_get_search_display_param() {
  $search_parameters = array(
    'search_networks',
    'search_studies',
    'search_datasets',
    'search_variables'
  );
  $search_param = array();
  foreach ($search_parameters as $search_param_val) {
    $search_param[$search_param_val] = variable_get_value($search_param_val);
  }

  return $search_param;
}

function obiba_mica_search_variable_page_search() {
  //drupal_set_title(t('@request variables search', array('@request' => ucwords($request))));

  if (!obiba_mica_commons_is_ajax()) {
    _get_search_data();
    $url_param = explode('?', request_uri());

    if (!empty($url_param[1])) {
      return drupal_goto(request_path(), array(
        'fragment' => '!' . $url_param[1]
      ), 302);
    }

    obiba_mica_search_load_libs();

    return theme('obiba_mica_search_search', array());
  }

  $output = theme('obiba_mica_search_search', _get_search_data()); //populates facets session values

  return drupal_json_output(array(
    'facets' => _get_facets_theme(),
    'searchResult' => $output
  ));
}

function _get_search_data() {
  $studies = NULL;
  $study_charts = NULL;
  $variables = NULL;
  $networks = NULL;
  $datasets = NULL;
  $variable_charts = NULL;
  $join_query_response = NULL;
  $search_resources = new MicaSearchResource();

  $resource = obiba_mica_search_get_url_tab_parameter();
  if (!empty($resource)) {
    switch ($resource) {
      case  'networks':
        $join_query_response = $search_resources->search_networks();
        $networks = $join_query_response->getNetworkResponseWrapper();
        extract(obiba_mica_get_hits_entities_variable($join_query_response->getCountStats()), EXTR_OVERWRITE);
        break;
      case  'datasets':
        $join_query_response = $search_resources->search_datasets();
        $datasets = $join_query_response->getDatasetResponseWrapper();
        extract(obiba_mica_get_hits_entities_variable($join_query_response->getCountStats()), EXTR_OVERWRITE);
        break;
      case  'studies':
        $join_query_response = $search_resources->search_studies();
        $studies = $join_query_response->getStudyResponseWrapper();
        extract(obiba_mica_get_hits_entities_variable($join_query_response->getCountStats()), EXTR_OVERWRITE);
        break;
      case  'variables' :
        $join_query_response = $search_resources->search_variables();
        $variables = $join_query_response->getVariableResponseWrapper();
        extract(obiba_mica_get_hits_entities_variable($join_query_response->getCountStats()), EXTR_OVERWRITE);
        break;
    }

  }
  else {
    $join_query_response = $search_resources->search_variables();
    $variables = $join_query_response->getVariableResponseWrapper();
  }

  $url_parm = explode('?', request_uri());
  if (!empty($url_parm[1])) {
    parse_str($url_parm[1], $parts);
  }

  return array(
    'variable_select_size_form' => drupal_get_form('obiba_mica_search_size_select_form'),
    'search_param' => _obiba_mica_search_get_search_display_param(),
    'noval' => '',
    'query' => empty($parts['query']) ? '' : $parts['query'],
    'variables_result' => array('data' => obiba_mica_search_variables_table($variables)),
    'variable_total_hits' => !empty($variable_total_hits) ? $variable_total_hits : NULL,
    'variable_total_count' => !empty($variable_total_count) ? $variable_total_count : NULL,
    'variable_search_form' => drupal_get_form('obiba_mica_commons_create_full_text_query_form', 'variables'),
    'datasets' => array('data' => obiba_mica_search_datasets_table($datasets)),
    'dataset_total_hits' => !empty($dataset_total_hits) ? $dataset_total_hits : NULL,
    'dataset_total_count' => !empty($dataset_total_count) ? $dataset_total_count : NULL,
    'dataset_select_size_form' => drupal_get_form('obiba_mica_search_size_select_form'),
    'dataset_search_form' => drupal_get_form('obiba_mica_commons_create_full_text_query_form', 'datasets'),
    'studies' => array('data' => obiba_mica_search_studies_table($studies)),
    'study_total_hits' => !empty($study_total_hits) ? $study_total_hits : NULL,
    'study_total_count' => !empty($study_total_count) ? $study_total_count : NULL,
    'study_select_size_form' => drupal_get_form('obiba_mica_search_size_select_form'),
    'study_search_form' => drupal_get_form('obiba_mica_commons_create_full_text_query_form', 'studies'),
    'networks' => array('data' => obiba_mica_search_networks_table($networks)),
    'network_total_hits' => !empty($network_total_hits) ? $network_total_hits : NULL,
    'network_total_count' => !empty($network_total_count) ? $network_total_count : NULL,
    'network_select_size_form' => drupal_get_form('obiba_mica_search_size_select_form'),
    'network_search_form' => drupal_get_form('obiba_mica_commons_create_full_text_query_form', 'networks'),
  );
}

function obiba_mica_search_size_select_form() {
  $context =
    array(
      'options' => //
        array( //
          10 => 10,
          20 => 20,
          25 => 25,
          50 => 50,
          100 => 100
        ) //
    );

  return obiba_mica_commons_create_size_select_form($context);
}

function obiba_mica_search_coverage_page() {

  if (!obiba_mica_commons_is_ajax()) {
    $url_param = explode('?', request_uri());

    if (!empty($url_param[1])) {
      return drupal_goto(request_path(), array(
        'fragment' => '!' . $url_param[1]
      ), 302);
    }

    obiba_mica_search_load_libs();
    return theme('obiba_mica_search_coverage', array());
  }

  $url_param = explode('?', request_uri());

  if (!empty($url_param[1])) {
    parse_str($url_param[1], $parts);
  }

  $group_by = !empty($parts['group-by']) ? $parts['group-by'] : 'studyIds';
  $taxonomy = $parts['taxonomy'];

  $coverages_data = _obiba_mica_search_get_coverage_data(!empty($parts['query']) ? $parts['query'] : NULL, $group_by, $taxonomy);

  if (empty($taxonomy)) {
    $output = theme('obiba_mica_search_coverage', $coverages_data);

    return drupal_json_output(array(
      'facets' => empty($parts['with-facets']) || strtolower($parts['with-facets']) !== "false" ? _get_facets_theme() : NULL,
      'searchResult' => $output,
      'coverageTaxonomies' => array_values(array_map(function($c) {return $c->taxonomy->name;}, $coverages_data['coverages']->taxonomies)),
      'aggsDictionary' => empty($parts['with-facets']) || strtolower($parts['with-facets']) !== "false" ? obiba_mica_search_create_aggs_dictionary() : NULL
    ));
  } else {
    $output = theme('obiba_mica_search_coverage_taxonomy', $coverages_data);

    return drupal_json_output(array(
      'coverageTaxonomyResult' => $output
    ));
  }
}

/**
 * Extract from the given coverage (can be term or vocabulary or taxonomy coverage) the bucket with the specified value.
 * @param $coverage
 * @param $bucket_name
 * @return bool
 */
function _obiba_mica_search_get_coverage_bucket($coverage, $bucket_value) {
  if (!empty($coverage->buckets)) {
    foreach ($coverage->buckets as $bucket) {
      if ($bucket->value == $bucket_value) {
        return $bucket;
      }
    }
  }
  return FALSE;
}

/**
 * Merge buckets from all taxonomies.
 * @param $coverages
 * @return array
 */
function _obiba_mica_search_get_all_buckets($coverages) {
  $all_buckets = array();
  if (empty($coverages->taxonomies)) {
    return $all_buckets;
  }

  foreach ($coverages->taxonomies as $taxonomy_coverage) {
    if (!empty($taxonomy_coverage->buckets)) {
      foreach ($taxonomy_coverage->buckets as $bucket) {
        $found = FALSE;
        foreach ($all_buckets as $merged_bucket) {
          if ($merged_bucket->value == $bucket->value) {
            // increment hits and count
            $merged_bucket->hits = $merged_bucket->hits + (!empty($bucket->hits) ? $bucket->hits : 0);
            $merged_bucket->count = $merged_bucket->count + (!empty($bucket->count) ? $bucket->count : 0);
            $found = TRUE;
            break;
          }
        }
        if (!$found) {
          // make a copy
          $merged_bucket = new stdClass();
          $merged_bucket->field = $bucket->field;
          $merged_bucket->value = $bucket->value;
          $merged_bucket->hits = !empty($bucket->hits) ? $bucket->hits : 0;
          $merged_bucket->count = !empty($bucket->count) ? $bucket->count : 0;
          $merged_bucket->title = $bucket->title;
          $merged_bucket->description = $bucket->description;
          $all_buckets[] = $merged_bucket;
        }
      }
    }
  }

  return $all_buckets;
}

function _obiba_mica_search_get_coverage_data($query, $group_by, $taxonomy) {
  $vocabulary_coverage_output = array();
  $search_resources = new MicaSearchResource();

  if(empty($taxonomy) || !isset($_SESSION['coverages'])) {
    unset($_SESSION['coverages']);
    $coverages = $search_resources->taxonomies_coverage(NULL, array('group-by' => 'studyIds'));
    $_SESSION['coverages'] = $coverages;
    $_SESSION['fixed_menu'] = array('coverages' => $coverages);
  }

  if(!empty($taxonomy)) {
    $coverages = $_SESSION['coverages'];
  }

  if (!empty($coverages->taxonomies) && !empty($taxonomy)) {
    foreach ($coverages->taxonomies as $t) {
      if ($t->taxonomy->name === $taxonomy) {
        $taxonomy_coverage = $t;
        break;
      }
    }

    if (!empty($taxonomy_coverage)) {
      $all_buckets = _obiba_mica_search_get_all_buckets($coverages);

      foreach ($taxonomy_coverage->vocabularies as $vocabulary_coverage) {
        $vocabulary_coverage_output[$vocabulary_coverage->vocabulary->name] = theme('obiba_mica_search_vocabulary_coverage', array(
          'taxonomy' => $taxonomy_coverage->taxonomy,
          'vocabulary_coverage' => $vocabulary_coverage,
          'all_buckets' => $all_buckets,
          'vocabulary_attribute' => 'attributes-' . $taxonomy_coverage->taxonomy->name . '__' . $vocabulary_coverage->vocabulary->name . '-und',
          'bucket_type' => $group_by == 'studyIds' ? 'studies' : 'variables',
          'group_by' => $group_by
        ));
      }
    }
  }

  MicaClient::order_taxonomies($coverages->taxonomies, function ($value) {
    return $value->taxonomy->name;
  });

  return array(
    'variable_search_form' => drupal_get_form('obiba_mica_commons_create_full_text_query_form', 'variables'),
    'coverages' => $coverages,
    'taxonomy_coverage' => $taxonomy_coverage,
    'vocabulary_coverage_output' => $vocabulary_coverage_output,
    'query' => $query,
    'group_by' => $group_by,
  );
}

function obiba_mica_search_coverage_download() {
  $content_mime = 'text/csv';
  $content_disposition = 'attachment; filename="classification.csv"';

  $search_resources = new MicaSearchResource();
  $response = $search_resources->download_taxonomies_coverage(drupal_get_query_parameters(), array('group-by' => 'studyIds'));

  if (!empty($response)) {
    $headers = $search_resources->getLastResponseHeaders();
    $content_mime = $headers['Content-Type'][0];
    $content_disposition = $headers['Content-Disposition'][0];
    $copyright_notice = variable_get_value('mica_copyright_notice');
    $output = !empty($copyright_notice) ? '"' . t($copyright_notice) . '"' . chr(13) : '';
    $output .= $response->body;
  }

  drupal_add_http_header('Content-Type', $content_mime . '; utf-8');
  drupal_add_http_header('Content-Disposition', $content_disposition);
  ob_clean();
  print $output;
  exit;
}

function obiba_mica_search_study_page_search() {
  $output['title'] = t('Study search page');
  obiba_mica_search_load_libs();
  $search_resources = new MicaSearchResource();
  $search_response = $search_resources->search_studies();
  $study_charts = theme('obiba_mica_search_charts', array(
    'charts' => obiba_mica_search_get_facets_chart('obiba_mica_study', $_SESSION['studies']['aggregations'])
  ));
  return $study_charts . obiba_mica_search_studies_table($search_response);
}

function obiba_mica_search_variables_table($variables) {
  $rows = array();
  $total_hits = 0;
  $has_study = FALSE;

  if (!empty($variables)) {
    $total_hits = $variables->getTotalHits();
    $summaries = $variables->getSummaries();
    foreach ($summaries as $variable) {
      $name = $variable->name;
      $dataset_name = !empty($variable->datasetAcronym) ?
        obiba_mica_commons_get_localized_field($variable, 'datasetAcronym') :
        $variable->datasetId;
      $dataset_type = $variable->variableType == 'Study' ? 'study-dataset' : 'harmonization-dataset';
      $study_name = !empty($variable->studyAcronym) ? obiba_mica_commons_get_localized_field($variable, 'studyAcronym') : NULL;
      $variable_label = !empty($variable->variableLabel) ? obiba_mica_commons_get_localized_field($variable, 'variableLabel') : NULL;

      $row = array(
        l($name, 'mica/variable/' . $variable->id),
        !empty($variable_label) ? $variable_label : '-',
      );

      $display_study_column = variable_get_value('variables_column_study');
      if (!empty($display_study_column)) {
        if (!empty($variable->studyId)) {
          $row[] = l($study_name, 'mica/study/' . $variable->studyId);
          $has_study = TRUE;
        }
      }

      $display_dataset_column = variable_get_value('variables_column_dataset');
      if (!empty($display_dataset_column)) {
        $row[] = l($dataset_name, 'mica/' . $dataset_type . '/' . $variable->datasetId);
      }
      $rows[] = $row;
    }
  }

  // this is just a temporary trick to hide an empty column
  // study count with search link is expected instead
  if ($has_study && (!empty($display_study_column) || !empty($display_dataset_column))) {
    for ($i = 0; $i < count($rows); $i++) {
      if (count($rows[$i]) == 1 + ($display_study_column + $display_dataset_column)) {
        $rows[$i][] = '-';
      }
    }
  }

  $headers_param = _obiba_mica_search_get_header_variables_table($has_study);
  $headers = $headers_param['header'];

  pager_default_initialize($total_hits, MicaClient::getResponsePageSize());
  return '<div class="scroll-content-tab">' . theme(
    'table',
    array(
      'header' => $headers,
      'rows' => $rows,
      'empty' => t(variable_get_value('variables_empty_label'))
    )
  ) . '</div>' . theme('pager');
}

function _obiba_mica_search_get_header_variables_table($has_study = NULL) {
  $params_column_display = array(
    0 => '',
    1 => '',
    2 => variable_get_value('variables_column_study'),
    3 => variable_get_value('variables_column_dataset')
  );
  $headers = array();
  $headers[] = t('Name');
  $headers[] = t('Label');
  if (!empty($has_study) && !empty($params_column_display[2])) {
    $headers[] = t('Study');
  }
  if (!empty($params_column_display[3])) {
    $headers[] = t('Dataset');
  }
  $headers_params['header'] = $headers;
  $headers_params['params'] = $params_column_display;
  return $headers_params;
}

function _obiba_mica_search_get_sub_header_studies_table() {
  $rows_column = array();
  $headers = array();
  $column_studies_param = array(
    0 => '',
    1 => '',
    2 => variable_get_value('studies_column_design'),
    3 => variable_get_value('studies_column_questionnaire'),
    4 => variable_get_value('studies_column_pm'),
    5 => variable_get_value('studies_column_bio'),
    6 => variable_get_value('studies_column_other'),
    7 => variable_get_value('studies_column_participants'),
    8 => variable_get_value('studies_column_networks'),
    9 => variable_get_value('studies_column_study_datasets'),
    10 => variable_get_value('studies_column_harmonization_datasets'),
    11 => variable_get_value('studies_column_variables')
  );
  $headers[] = array('data' => t('Acronym'), 'class' => 'col-sm-1');
  $rows_column[] = '';
  $headers[] = array('data' => t('Name'), 'class' => 'col-sm-3');
  $rows_column[] = '';

  if ($column_studies_param[2]) {
    $headers[] = t('Design');
    $rows_column[] = '';
  }
  $colspan_datasources = $column_studies_param[3] + $column_studies_param[4] + $column_studies_param[5] + $column_studies_param[6];

  if ($colspan_datasources > 0) {
    $headers[] = array(
      'data' => t('Data Sources Available'),
      'colspan' => $colspan_datasources,
      'class' => 'checkbox'
    );

    if (!empty($column_studies_param[3])) {
      $rows_column[] = array('data' => t('Quest'), 'title' => t('Questionnaires'));
    }
    if (!empty($column_studies_param[4])) {
      $rows_column[] = array('data' => t('PM'), 'title' => t('Physical Measures'));
    }
    if (!empty($column_studies_param[5])) {
      $rows_column[] = array('data' => t('Bio'), 'title' => t('Biological Samples'));
    }
    if (!empty($column_studies_param[6])) {
      $rows_column[] = t('Others');
    }
  }
  if ($column_studies_param[7]) {
    $headers[] = array('data' => t('Participants'));
    $rows_column[] = '';
  }
  if ($column_studies_param[8]) {
    $headers[] = array('data' => t('Networks'));
    $rows_column[] = '';
  }

  $colspan_datasets = $column_studies_param[9] + $column_studies_param[10];
  if ($colspan_datasets > 0) {
    $headers[] = array('data' => t('Datasets'), 'colspan' => $colspan_datasets);
    if (!empty($column_studies_param[9])) {
      $rows_column[] = t('Study');
    }
    if (!empty($column_studies_param[10])) {
      $rows_column[] = t('Harmonization');
    }
  }

  if (!empty($column_studies_param[11])) {
    $headers[] = array('data' => t('Variables'));
    $rows_column[] = '';
  }
  if ($colspan_datasets == 0 && $colspan_datasources == 0) {
    $rows_column = NULL;
  }
  $headers_columns['headers'] = $headers;
  $headers_columns['rows_column'] =
    empty($rows_column)
      ? NULL
      : array('data' => $rows_column, 'class' => array('table-secondary-header'));

  return $headers_columns;
}

function obiba_mica_search_studies_table($studies) {
  $rows = array();

  if (!empty($studies)) {
    $total_hits = $studies->getTotalHits();
    $summaries = $studies->getSummaries();

    $headers_columns = _obiba_mica_search_get_sub_header_studies_table();

    if ($total_hits > 0 && !empty($headers_columns['rows_column'])) {
      $rows[] = $headers_columns['rows_column'];
    }

    foreach ($summaries as $study) {
      $column_row = array();
      $query_studies_param =
        MicaClient::add_parameter_dto_query_link(array(
          'studies' => array('terms' => array('studyIds' => $study->id))
        ));

      $query_studies_param_harmo =
        MicaClient::add_parameter_dto_query_link(array(
          'variables' =>
            array('terms' => array('studyIds' => $study->id, 'variableType' => 'dataschema'))
        ));

      $query_studies_param_dataset =
        MicaClient::add_parameter_dto_query_link(array(
          'variables' =>
            array('terms' => array('studyIds' => $study->id, 'variableType' => 'study'))
        ));

      $number_variables = obiba_mica_commons_format_number($study->{'obiba.mica.CountStatsDto.studyCountStats'}->variables);
      //MicaClient::obiba_mica_search_get_item_count('studies', 'variables', $study->id);

      $number_tables_study_harmo = $study->{'obiba.mica.CountStatsDto.studyCountStats'}->harmonizationDatasets;
      //    MicaClient::obiba_mica_search_get_item_count('studies', 'studyTables-studyId', $study->id);
      $number_table_study_study = $study->{'obiba.mica.CountStatsDto.studyCountStats'}->studyDatasets;
      // MicaClient::obiba_mica_search_get_item_count('studies', 'studyTable-studyId', $study->id);

      $number_networks_study = $study->{'obiba.mica.CountStatsDto.studyCountStats'}->networks;
      // MicaClient::obiba_mica_search_get_item_count('studies', 'networks-studyId', $study->id);

      $name = obiba_mica_commons_get_localized_field($study, 'name');

      $column_row[] = l(obiba_mica_commons_get_localized_field($study, 'acronym'), 'mica/study/' . $study->id);
      $column_row[] = $name;
      $study_column_design = variable_get_value('studies_column_design');
      if (!empty($study_column_design)) {
        $column_row[] = implode(', ', obiba_mica_commons_clean_string($study->designs));
      }

      $study_column_quest = variable_get_value('studies_column_questionnaire');
      if (!empty($study_column_quest)) {
        $column_row[] = array(
          'data' => !empty($study->dataSources) && obiba_mica_search_has_datasource($study->dataSources, 'questionnaires') ?
              '<i class="glyphicon glyphicon-ok"></i>' : '-',
          'class' => 'checkbox'
        );
      }
      $study_column_pm = variable_get_value('studies_column_pm');
      if (!empty($study_column_pm)) {
        $column_row[] = array(
          'data' => !empty($study->dataSources) && obiba_mica_search_has_datasource($study->dataSources, 'physical_measures') ?
              '<i class="glyphicon glyphicon-ok"></i>' : '-',
          'class' => 'checkbox'
        );
      }
      $study_column_bio = variable_get_value('studies_column_bio');
      if (!empty($study_column_bio)) {
        $column_row[] = array(
          'data' => !empty($study->dataSources) && obiba_mica_search_has_datasource($study->dataSources, 'biological_samples') ?
              '<i class="glyphicon glyphicon-ok"></i>' : '-',
          'class' => 'checkbox'
        );
      }
      $study_column_other = variable_get_value('studies_column_other');
      if (!empty($study_column_other)) {
        $column_row[] = array(
          'data' => !empty($study->dataSources) && obiba_mica_search_has_datasource($study->dataSources, 'others') ?
              '<i class="glyphicon glyphicon-ok"></i>' : '-',
          'class' => 'checkbox'
        );
      }
      $study_column_participant = variable_get_value('studies_column_participants');
      if (!empty($study_column_participant)) {
        $column_row[] = isset($study->targetNumber->noLimit) ? t('No Limit') :
          isset($study->targetNumber->number) ? obiba_mica_commons_format_number($study->targetNumber->number) : NULL;
      }
      $study_column_networks = variable_get_value('studies_column_networks');
      if (!empty($study_column_networks)) {
        $column_row[] = !empty($number_networks_study) ?
          l($number_networks_study, 'mica/search', array(
            'query' => array(
              'type' => 'networks',
              'query' => $query_studies_param
            )
          )) : '-';
      }
      $study_column_study_datasets = variable_get_value('studies_column_study_datasets');
      if (!empty($study_column_study_datasets)) {
        $column_row[] = !empty($number_table_study_study) ? l($number_table_study_study, 'mica/search', array(
          'query' => array(
            'type' => 'datasets',
            'query' => $query_studies_param_dataset
          )
        )) : '-';
      }
      $study_column_harmonization_datasets = variable_get_value('studies_column_harmonization_datasets');
      if (!empty($study_column_harmonization_datasets)) {
        $column_row[] = !empty($number_tables_study_harmo) ? l($number_tables_study_harmo, 'mica/search', array(
          'query' => array(
            'type' => 'datasets',
            'query' => $query_studies_param_harmo
          )
        )) : '-';
      }

      $study_column_variables = variable_get_value('studies_column_variables');
      if (!empty($study_column_variables)) {
        $column_row[] = !empty($number_variables) ?
          l($number_variables, 'mica/search', array(
            'query' => array(
              'type' => 'variables',
              'query' => $query_studies_param
            )
          ))
          : '-';
      }

      $rows[] = $column_row;
    }
    $headers = $headers_columns['headers'];
    pager_default_initialize($total_hits, MicaClient::getResponsePageSize());
    return '<div class="scroll-content-tab">' . theme(
      'table',
      array(
        'header' => $headers,
        'rows' => $rows,
        variable_get_value('studies_column_design'),
        'empty' => t(variable_get_value('studies_empty_label')),
        'attributes' => array(
          'id' => 'studies-results',
        )
      )
    ) . '</div>' . theme('pager');
  }
}

function obiba_mica_search_has_datasource($data_sources, $value) {
  foreach ($data_sources as $value_term) {
    if ($value_term == $value) {
      return TRUE;
    }
  }
  return FALSE;
}

function obiba_mica_search_datasets_table($datasets) {
  $rows = array();
  $total_hits = 0;

  if (!empty($datasets)) {
    $total_hits = $datasets->getTotalHits();
    $summaries = $datasets->getSummaries();
    foreach ($summaries as $dataset) {
      $row = array();
      $query_datasets_param =
        MicaClient::add_parameter_dto_query_link(array('variables' => array('terms' => array('datasetId' => $dataset->id))));

      $count_networks = !empty($dataset->{'obiba.mica.CountStatsDto.datasetCountStats'}->networks) ?
        $dataset->{'obiba.mica.CountStatsDto.datasetCountStats'}->networks : NULL;

      $count_studies = !empty($dataset->{'obiba.mica.CountStatsDto.datasetCountStats'}->studies) ?
        $dataset->{'obiba.mica.CountStatsDto.datasetCountStats'}->studies : NULL;

      $count_variables = !empty($dataset->{'obiba.mica.CountStatsDto.datasetCountStats'}->variables) ?
        obiba_mica_commons_format_number($dataset->{'obiba.mica.CountStatsDto.datasetCountStats'}->variables) : NULL;

      if (!empty($dataset->{'obiba.mica.StudyDatasetDto.type'})) {
        $type_dataset_link = 'study-dataset';
        $type_dataset = t('Study');
      }
      else {
        $type_dataset_link = 'harmonization-dataset';
        $type_dataset = t('Harmonization');
      }
      $name = obiba_mica_commons_get_localized_field($dataset, 'name');
      $row[] = l(obiba_mica_commons_get_localized_field($dataset, 'acronym'), 'mica/' . $type_dataset_link . '/' . $dataset->id);
      $row[] = $name;
      $dataset_column_type = variable_get_value('datasets_column_type');
      if (!empty($dataset_column_type)) {
        $row[] = $type_dataset;
      }
      $dataset_column_networks = variable_get_value('datasets_column_networks');
      if (!empty($dataset_column_networks)) {
        $row[] = !empty($count_networks) ?
          l($count_networks, 'mica/search', array(
            'query' => array(
              'type' => 'networks',
              'query' => $query_datasets_param
            )
          ))
          : '-';
      }
      $dataset_column_studies = variable_get_value('datasets_column_studies');
      if (!empty($dataset_column_studies)) {
        $row[] = !empty($count_studies) ?
          l($count_studies, 'mica/search', array(
            'query' => array(
              'type' => 'studies',
              'query' => $query_datasets_param
            )
          ))
          : '-';
      }
      $dataset_column_variables = variable_get_value('datasets_column_variables');
      if (!empty($dataset_column_variables)) {
        $row[] = !empty($count_variables) ?
          l($count_variables, 'mica/search', array(
            'query' => array(
              'type' => 'variables',
              'query' => $query_datasets_param
            )
          ))
          : '-';
      }
      $rows[] = $row;
    }

  }

  $headers = _obiba_mica_search_get_header_datasets_table();

  pager_default_initialize($total_hits, MicaClient::getResponsePageSize());
  return '<div class="scroll-content-tab">' . theme(
    'table',
    array(
      'header' => $headers,
      'rows' => $rows,
      'empty' => t(variable_get_value('datasets_empty_label')),
    )
  ) . '</div>' . theme('pager');
}

function _obiba_mica_search_get_header_datasets_table() {
  $params_column_display = array(
    0 => '',
    1 => '',
    2 => variable_get_value('datasets_column_type'),
    3 => variable_get_value('datasets_column_networks'),
    4 => variable_get_value('datasets_column_studies'),
    5 => variable_get_value('datasets_column_variables')
  );
  $headers = array();
  $headers[] = t('Acronym');
  $headers[] = t('Name');
  if (!empty($params_column_display[2])) {
    $headers[] = t('Type');
  }
  if (!empty($params_column_display[3])) {
    $headers[] = t('Networks');
  }
  if (!empty($params_column_display[4])) {
    $headers[] = t('Studies');
  }
  if (!empty($params_column_display[5])) {
    $headers[] = t('Variables');
  }
  return $headers;
}

function _obiba_mica_search_get_sub_header_networks_table() {
  $rows_column = array(
    0 => '',
    1 => '',
    2 => '',
    3 => '',
    4 => '',
    5 => '',
  );

  $headers = array();
  $column_networks_param = array(
    0 => '',
    1 => '',
    2 => variable_get_value('networks_column_studies'),
    3 => variable_get_value('networks_column_study_datasets'),
    4 => variable_get_value('networks_column_harmonization_datasets'),
    5 => variable_get_value('networks_column_variables')
  );

  $headers[] = t('Acronym');
  $headers[] = t('Name');

  if (!empty($column_networks_param[2])) {
    $headers[] = t('Studies');
  }

  $colspan = 0;

  if (!empty($column_networks_param[3])) {
    $rows_column[3 + $colspan] = t('Study');
    $colspan++;
  }

  if (!empty($column_networks_param[4])) {
    $rows_column[3 + $colspan] = t('Harmonization');
    $colspan++;
  }

  if ($colspan > 0) {
    $headers[] = array('data' => t('Datasets'), 'colspan' => $colspan);
    // make sure headers and 2nd header have same # of columns
    if ($colspan == 1) {
      array_pop($rows_column);
    }
  }

  if (!empty($column_networks_param[5])) {
    $headers[] = t('Variables');
  }

  $headers_columns['headers'] = $headers;
  $headers_columns['rows_column'] =
    empty($rows_column[3]) && empty($rows_column[4])
      ? NULL
      : array('data' => $rows_column, 'class' => array('table-secondary-header'));

  return $headers_columns;
}

function obiba_mica_search_networks_table($networks) {
  $rows = array();
  if (!empty($networks)) {
    $total_hits = $networks->getTotalHits();
    $headers_columns = _obiba_mica_search_get_sub_header_networks_table();
    if ($total_hits > 0 && !empty($headers_columns['rows_column'])) {
      $rows[] = $headers_columns['rows_column'];
    }

    $summaries = $networks->getSummaries();
    foreach ($summaries as $network) {
      $rows_columns = array();
      $param_network_query =
        MicaClient::add_parameter_dto_query_link(array('networks' => array('terms' => array('id' => $network->id))));

      $param_network_query_harmo_dataset =
        MicaClient::add_parameter_dto_query_link(
          array(
            'networks' => array('terms' => array('id' => $network->id)),
            'variables' => array('terms' => array('variableType' => 'dataschema'))
          )
        );

      $param_network_query_study_dataset =
        MicaClient::add_parameter_dto_query_link(
          array(
            'networks' => array('terms' => array('id' => $network->id)),
            'variables' => array('terms' => array('variableType' => 'study'))
          )
        );

      $studies_count = !empty($network->{'obiba.mica.CountStatsDto.networkCountStats'}->studies) ?
        $network->{'obiba.mica.CountStatsDto.networkCountStats'}->studies : NULL;

      $datasets_study_count = !empty($network->{'obiba.mica.CountStatsDto.networkCountStats'}->studyDatasets) ?
        $network->{'obiba.mica.CountStatsDto.networkCountStats'}->studyDatasets : NULL;

      $datasets_harmonized_count = !empty($network->{'obiba.mica.CountStatsDto.networkCountStats'}->harmonizationDatasets) ?
        $network->{'obiba.mica.CountStatsDto.networkCountStats'}->harmonizationDatasets : NULL;

      $variables_count = !empty($network->{'obiba.mica.CountStatsDto.networkCountStats'}->variables) ?
        obiba_mica_commons_format_number($network->{'obiba.mica.CountStatsDto.networkCountStats'}->variables) : NULL;

      $name = obiba_mica_commons_get_localized_field($network, 'name');

      if ($total_hits > 0) {
        $rows_columns[] = l(obiba_mica_commons_get_localized_field($network, 'acronym'), 'mica/network/' . $network->id);
        $rows_columns[] = $name;
        $column_studies = variable_get_value('networks_column_studies');
        if (!empty($column_studies)) {
          $rows_columns[] = l($studies_count, 'mica/search', array(
            'query' => array(
              'type' => 'studies',
              'query' => $param_network_query
            )
          ));
        }

        $column_study_dataset = variable_get_value('networks_column_study_datasets');
        if (!empty($column_study_dataset)) {
          $rows_columns[] = empty($datasets_study_count) ? '-' : l($datasets_study_count, 'mica/search', array(
            'query' => array(
              'type' => 'datasets',
              'query' => $param_network_query_study_dataset
            )
          ));
        }
        $column_harmonization_dataset = variable_get_value('networks_column_harmonization_datasets');
        if (!empty($column_harmonization_dataset)) {
          $rows_columns[] = empty($datasets_harmonized_count) ? '-' : l($datasets_harmonized_count, 'mica/search', array(
            'query' => array(
              'type' => 'datasets',
              'query' => $param_network_query_harmo_dataset
            )
          ));
        }
        $column_variables = variable_get_value('networks_column_variables');
        if (!empty($column_variables)) {
          $rows_columns[] = empty($variables_count) ? '-' : l($variables_count, 'mica/search', array(
            'query' => array(
              'type' => 'variables',
              'query' => $param_network_query
            )
          ));
        }
        $rows[] = $rows_columns;
      }
    }
    $headers = $headers_columns['headers'];

    pager_default_initialize($total_hits, MicaClient::getResponsePageSize());

    return '<div class="scroll-content-tab">' . theme(
      'table',
      array(
        'header' => $headers,
        'rows' => $rows,
        'empty' => t(variable_get_value('networks_empty_label')),
        'attributes' => array(
          'id' => 'networks-results',
        )
      )
    ) . '</div>' . theme('pager');
  }
}

function obiba_mica_search_get_studies_count_from_dto($dto) {
  $studies = array();
  $count_study = 0;
  $study_ids = array();
  foreach ($dto->studyIds as $study_id) {
    $studies['count'] = ++$count_study;
    $study_ids[] = $study_id;
  }
  $studies['ids'] = $study_ids;
  return $studies;
}

function obiba_mica_search_get_variables_count_from_studies_dto($studies) {
  $varcount = 0;
  foreach ($_SESSION['variables']['aggregations'] as $aggregation) {
    if ($aggregation->aggregation == 'studyIds') {
      foreach ($aggregation->{'obiba.mica.TermsAggregationResultDto.terms'} as $study) {
        if (in_array($study->key, $studies)) {
          $varcount += $study->count;
        }
      }
      return $varcount;
    }
  }
}

function _obiba_mica_search_facet_expand_strategy() {
  // count of zero signifies all taxonomies are included
  return !variable_get_value('studies_facet_search') && MicaClient::get_taxonomies_count() === 1
    ? ObibaFacetSearchBlockConstants::EXPAND_ALL
    : NULL;
}


