<?php
/*
 * Copyright (c) 2015 OBiBa. All rights reserved.
 *
 * This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

function obiba_mica_data_access_request_menu() {
  $items = array();

  $items['data-access-request'] = array(
    'page callback' => 'obiba_mica_data_access_request_form_page',
    'access callback' => TRUE,
//    'page arguments' => array(2)
  );
  $items['data-access-request-list'] = array(
    'page callback' => 'obiba_mica_data_access_request_list_page',
    'access callback' => TRUE,
//    'page arguments' => array(2)
  );

  $items['data-access-request-ng-list'] = array(
    'page callback' => 'obiba_mica_data_access_request_ng_list',
    'access callback' => TRUE,
    'file' => 'obiba_mica_data_access_request_service.inc',
  );

  $items['data-access'] = array(
    'title' => 'Data Access',
    'description' => 'Data access page',
    'page callback' => 'obiba_mica_data_access_request_page',
    'access callback' => TRUE,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
    'weight' => 4
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function obiba_mica_data_access_request_theme($existing, $type, $theme, $path) {
  $path_theme = $path . '/templates';
  return array(
    'obiba_mica_data_access_request-form-page' => array(
      'template' => 'obiba_mica_data_access_request-form-page',
      'path' => $path_theme
    ),
    'obiba_mica_data_access_request-page-data-access' => array(
      'template' => 'obiba_mica_data_access_request-page-data-access',
      'path' => $path_theme
    ),
    'obiba_mica_data_access_request-list' => array(
      'template' => 'obiba_mica_data_access_request-list',
      'path' => $path_theme
    )
  );
}

/**
 * Implements hook_library().
 */
function obiba_mica_data_access_request_library() {
  return obiba_mica_load_angular_library();
}

/**
 * Implements hook_library_alter().
 * Angular library compatible with Jquery 1.10
 *
 */
function obiba_mica_data_access_request_library_alter(&$javascript, $module) {
  if (($module == 'obiba_mica_data_access_request' || $module == 'system') && current_path() == 'data-access-request') {
    $path = drupal_get_path('module', 'jquery_update');
    jquery_update_jquery_replace($javascript, NULL, $path, NULL, '1.10');
  }

}

function obiba_mica_data_access_request_page() {
  global $user;
  $data_access_form_display = FALSE;
  $data_access_register_user = FALSE;
  $node_rendred = node_view(node_load(variable_get('access_request_page')));
  drupal_set_title($node_rendred['#node']->title);
  $node_rendred['#node']->title = '';
  if (user_is_logged_in()) {
    $data_access_form_display = TRUE;
  }
  else {
    $data_access_register_user = TRUE;
  }
  return theme('obiba_mica_data_access_request-page-data-access', array(
    'node_content' => $node_rendred,
    'data_access_form_display' => $data_access_form_display,
    'data_access_register_user' => $data_access_register_user
  ));
}

function obiba_mica_data_access_request_form_page() {
  $form_attributes = obiba_mica_data_access_request_form_get_config();
  if (!empty($form_attributes->responseCode) && $form_attributes->responseCode != 200) {
    dpm($form_attributes);
  }
  else {
    dpm($form_attributes);
    obiba_mica_load_libraires_resources('obiba_mica_data_access_request');
    $module_path_ = drupal_get_path('module', 'obiba_mica_data_access_request');
    drupal_add_js($module_path_ . '/js/ang/app.js', array('type' => 'file', 'scope' => 'footer'));
    drupal_add_js(array(
        'form' => $form_attributes->definition,
        'schema' => $form_attributes->schema
      ),
      'setting');
  }
  return theme('obiba_mica_data_access_request-form-page');
}

function obiba_mica_data_access_request_form_get_config() {
  $mica_client = new MicaDataAccessRequestResource();
  $config = $mica_client->get_form_definition();
  return $config;
}

function obiba_mica_data_access_request_list_page() {
  obiba_mica_load_libraires_resources('obiba_mica_data_access_request');
  $module_path_ = drupal_get_path('module', 'obiba_mica_data_access_request');
  drupal_add_js($module_path_ . '/js/ang/data-access-request.js', array('type' => 'file', 'scope' => 'footer'));
  drupal_add_js($module_path_ . '/js/ang/data-access-request-controller.js', array(
    'type' => 'file',
    'scope' => 'footer'
  ));
  drupal_add_js($module_path_ . '/js/ang/data-access-request-router.js', array('type' => 'file', 'scope' => 'footer'));
  drupal_add_js($module_path_ . '/js/ang/data-access-request-service.js', array('type' => 'file', 'scope' => 'footer'));

  return theme('obiba_mica_data_access_request-list');

}


