<?php

/*
 * @file  code for obiba_mica_data_access_request module
 * */

function obiba_mica_data_access_request_menu() {
  $items = array();

  $items['data-access-request'] = array(
    'page callback' => 'obiba_mica_data_access_request_form_page',
    'access callback' => TRUE,
//    'page arguments' => array(2)
  );
  $items['data-access'] = array(
    'title' => 'Data Access',
    'description' => 'Data access page',
    'page callback' => 'obiba_mica_data_access_request_page',
    'access callback' => TRUE,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
    'weight' => 4
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function obiba_mica_data_access_request_theme($existing, $type, $theme, $path) {
  $path_theme = $path . '/templates';
  return array(
    'obiba_mica_data_access_request-form-page' => array(
      'template' => 'obiba_mica_data_access_request-form-page',
      'path' => $path_theme
    )
  );
}

/**
 * Implements hook_library().
 */
function obiba_mica_data_access_request_library() {
  return obiba_mica_load_angular_library();
}

function obiba_mica_data_access_request_library_alter(&$javascript, $module) {
  if ($module = 'obiba_mica_data_access' && current_path() == 'data_access_request') {
    $path = drupal_get_path('module', 'jquery_update');
    jquery_update_jquery_replace($javascript, NULL, $path, NULL, '1.10');
  }
}

function obiba_mica_data_access_request_page() {
  $node_rendred = node_view(node_load(variable_get('access_request_page')));
  drupal_set_title($node_rendred['#node']->title);
  $node_rendred['#node']->title = '';
  return $node_rendred;
}

function obiba_mica_data_access_request_form_page() {
  $form_attributes = obiba_mica_data_access_request_form_get_config();
  if (!empty($form_attributes->responseCode) && $form_attributes->responseCode != 200) {
    dpm($form_attributes);
  }
  else {
    obiba_mica_load_libraires_resources('obiba_mica_data_access_request');
    $module_path_ = drupal_get_path('module', 'obiba_mica_data_access_request');
    drupal_add_js($module_path_ . '/js/ang/app.js', array('type' => 'file', 'scope' => 'footer'));
    drupal_add_js(array(
        'form' => $form_attributes->definition,
        'schema' => $form_attributes->schema
      ),
      'setting');
  }
  return theme('obiba_mica_data_access_request-form-page');
}

function obiba_mica_data_access_request_form_get_config() {
  $mica_client = new MicaDataAccessRequestResource();
  $config = $mica_client->get_form_definition();
  return $config;
}