<?php
/*
 * Copyright (c) 2015 OBiBa. All rights reserved.
 *
 * This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

function obiba_mica_data_access_request_menu() {
  $items = array();

  $items['mica/data-access'] = array(
    'title' => 'Data Access',
    'description' => 'Data access',
    'page callback' => 'obiba_mica_data_access_request_page',
    'access callback' => TRUE,
    'expanded' => TRUE,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
    'weight' => 4
  );

  $items['mica/data-access/home'] = array(
    'title' => t(variable_get('access_request_page_title', 'Data Access Request')),
    'page callback' => 'obiba_mica_data_access_request_page',
    'description' => 'Data access page',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'weight' => 2
  );

  $items['mica/data-access/requests'] = array(
    'title' => 'My Data Access Requests',
    'description' => 'List Data Access Requests',
    'page callback' => 'obiba_mica_data_access_request_list_page',
    'file' => 'obiba_mica_data_access_request_service.inc',
    'access callback' => 'obiba_mica_data_access_request_permission_check',
    'type' => MENU_NORMAL_ITEM,
    'weight' => 3
  );

  $items['mica/data-access/requests/ws'] = array(
    'page callback' => 'obiba_mica_data_access_requests_action',
    'access callback' => TRUE,
    'file' => 'obiba_mica_data_access_request_service.inc',
  );

  $items['mica/data-access/request/%/comments/ws'] = array(
    'page callback' => 'obiba_mica_data_access_request_comments_action',
    'access callback' => TRUE,
    'page arguments' => array(3),
    'file' => 'obiba_mica_data_access_request_service.inc',
  );

  $items['mica/data-access/request/%/comment/%/ws'] = array(
    'page callback' => 'obiba_mica_data_access_request_comment_action',
    'access callback' => TRUE,
    'page arguments' => array(3, 5),
    'file' => 'obiba_mica_data_access_request_service.inc',
  );

  $items['mica/data-access/request/%/_pdf/ws'] = array(
    'page callback' => 'obiba_mica_data_access_request_download_pdf',
    'access callback' => TRUE,
    'page arguments' => array(3),
    'file' => 'obiba_mica_data_access_request_service.inc',
  );

  $items['mica/data-access/request/%/attachments/%/_download/ws'] = array(
    'page callback' => 'obiba_mica_data_access_request_attachment',
    'access callback' => TRUE,
    'page arguments' => array(3, 5),
    'file' => 'obiba_mica_data_access_request_service.inc',
  );

  $items['mica/data-access/request/%/_status/%/ws'] = array(
    'page callback' => 'obiba_mica_data_access_request_update_request',
    'access callback' => TRUE,
    'page arguments' => array(3, 5),
    'file' => 'obiba_mica_data_access_request_service.inc',
  );

  $items['mica/data-access/request/upload-file'] = array(
    'page callback' => 'obiba_mica_data_access_request_upload_attachment',
    'access callback' => TRUE,
    'file' => 'obiba_mica_data_access_request_service.inc',
  );

  $items['mica/data-access/request/%/ws'] = array(
    'page callback' => 'obiba_mica_data_access_request_action',
    'access callback' => TRUE,
    'page arguments' => array(3),
    'file' => 'obiba_mica_data_access_request_service.inc',
  );

  $items['mica/data-access/request/file/%'] = array(
    'page callback' => 'obiba_mica_data_access_request_get_attachment',
    'access callback' => TRUE,
    'page arguments' => array(4),
    'file' => 'obiba_mica_data_access_request_service.inc',
  );

  $items['mica/data-access/data-access-form/ws'] = array(
    'page callback' => 'obiba_mica_data_access_request_form_get_config',
    'access callback' => TRUE,
    'file' => 'obiba_mica_data_access_request_service.inc',
  );

  $items['mica/data-access/request/delete/%/ws'] = array(
    'page callback' => 'obiba_mica_data_access_request_delete_request_access',
    'page arguments' => array(4),
    'file' => 'obiba_mica_data_access_request_service.inc',
    'access callback' => TRUE
  );

  $items['mica/data-access/request/redirect/%/%'] = array(
    'page callback' => 'obiba_mica_data_access_request_redirect',
    'page arguments' => array(4, 5),
    'file' => 'obiba_mica_data_access_request_service.inc',
    'access callback' => TRUE
  );

  return $items;
}

function obiba_mica_data_access_request_permission_check() {
  return obiba_mica_commons_is_authorized_agate_user();
}
/**
 * Implements hook_load_menus (obiba_main_app_angular_)
 */
function obiba_mica_data_access_request_load_menus() {
  $items = array();

  $items['mica/data-access/request'] = array(
    'access callback' => TRUE,
    'title' => t(variable_get('access_request_page_title', 'Data Access Request')),
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function obiba_mica_data_access_request_theme($existing, $type, $theme, $path) {
  $path_views_theme = $path . '/js/app/views';
  $path_theme = $path . '/templates';

  return array(
    'obiba_mica_data_access_request-form-page' => array(
      'template' => 'obiba_mica_data_access_request-form-page',
      'path' => $path_views_theme
    ),
    'obiba_mica_data_access_request-view-page' => array(
      'template' => 'obiba_mica_data_access_request-view-page',
      'path' => $path_views_theme
    ),
    'obiba_mica_data_access_request-histroy-view' => array(
      'template' => 'obiba_mica_data_access_request-histroy-view',
      'path' => $path_views_theme
    ),
    'data-access-request-validation-modal' => array(
      'template' => 'data-access-request-validation-modal',
      'path' => $path_views_theme
    ),
    'obiba_mica_data_access_request-page-data-access' => array(
      'template' => 'obiba_mica_data_access_request-page-data-access',
      'path' => $path_theme
    ),
    'obiba_mica_data_access_request-list' => array(
      'template' => 'obiba_mica_data_access_request-list',
      'path' => $path_theme
    )
  );
}

/**
 * Implements hook_library().
 */
function obiba_mica_data_access_request_library() {
  return obiba_main_app_angular_load_angular_library();
}

/**
 * Implements hook_library_alter().
 * Angular library compatible with Jquery 1.10
 *
 */
function obiba_mica_data_access_request_library_alter(&$javascript, $module) {
  if (($module == 'obiba_mica_data_access_request' || $module == 'system') && current_path() == 'mica/data-access/request') {
    $path = drupal_get_path('module', 'jquery_update');
    jquery_update_jquery_replace($javascript, NULL, $path, NULL, '1.10');
  }

}

/**
 * Create/Update data access request node content page
 */
function obiba_mica_data_access_request() {
  $data_access_node_node = obiba_mica_commons_get_translated_node(variable_get('access_request_page'));

  if (!empty($data_access_node_node)) {
    return $data_access_node_node;
  }
  else {
    $my_body_content = "<div> <p>Requests for further information on the datasets and requests for access are received by
the our Access Office. Prior to submitting a Data Access Application Form, we strongly recommend that you consult the
our Policy documents, that will provide you with detailed information about the process and our's access, publication
and intellectual property policies.</p> </div>";
    $access_request_node_page = obiba_mica_commons_add_page(t(variable_get('access_request_page')), $my_body_content);
    variable_set('access_request_page', $access_request_node_page->nid);
    return node_view(node_load(variable_get('access_request_page')));
  }
}

/**
 * @return string
 */
function obiba_mica_data_access_request_page() {

  $data_access_list_display = FALSE;
  $data_access_register_user = FALSE;

  $node_rendred = obiba_mica_data_access_request();
  drupal_set_title(t(variable_get_value('access_home_page_title')));

  $node_rendred['#node']->title = '';
  if (user_is_logged_in()) {
    $data_access_list_display = TRUE;
  }
  else {
    $data_access_register_user = TRUE;
  }

  return theme('obiba_mica_data_access_request-page-data-access', array(
    'node_content' => $node_rendred,
    'data_access_list_display' => $data_access_list_display,
    'data_access_register_user' => $data_access_register_user
  ));
}

/**
 * Implementation of hook_get_ng_module_to_load()
 */

function obiba_mica_data_access_request_get_ng_module_to_load() {
  return 'mica.DataAccessRequest';
}

/**
 * Implements hook_get_js()
 */
function obiba_mica_data_access_request_get_js() {
  $module_path = drupal_get_path('module', 'obiba_mica_data_access_request');
  $js = file_scan_directory($module_path . '/js/app', '/.*\.js$/', array('key' => 'name'));
  ksort($js);
  foreach ($js as $file_js) {
    drupal_add_js($file_js->uri, array('type' => 'file', 'scope' => 'footer'));
  }
}

function obiba_mica_data_access_requests_datatable_init($requests) {
  if (drupal_get_library('obiba_mica_dataset', 'datatables')) {
    drupal_add_library('obiba_mica_dataset', 'datatables');
  }
  else {
    obiba_mica_commons_datatables_external_source();
  }

  $requests = (new MicaDataAccessRequests(NULL, 'METHOD_GET'))->get_requests();

  drupal_add_js(drupal_get_path('module', 'obiba_mica_data_access_request') .
    '/js/obiba_mica_data_access_request_datatable_init.js', 'file');
  drupal_add_js(array(
    'table_headers' => array(
      array("title" => t('ID')),
      array("title" => t('Applicant')),
      array("title" => t('Title'), 'width' => '35%'),
      array("title" => t('Last Update')),
      array("title" => t('Submission Date')),
      array("title" => t('Status')),
      array("title" => t('Actions'))
    ),
    'table_data' => obiba_mica_data_access_request_table_rows($requests)
  ), 'setting');
}

function obiba_mica_data_access_request_table_rows($requests) {
  if (empty($requests->responseCode) && !empty($requests)) {
    $res = array_map(function ($r) {
      $r->submission_date = NULL;
      if ($r->status != 'OPENED') {
        foreach ($r->statusChangeHistory as $change) {
          if ($change->to == 'SUBMITTED') {
            $r->submission_date = $change->changedOn;
          }
        }
      }

      $r->full_name = _obiba_mica_data_access_request_profile_full_name($r);

      return array(
        l($r->id, 'mica/data-access/request', array('fragment' => '/view/' . $r->id)),
        $r->full_name,
        empty($r->title) ? '' : $r->title,
        date_format(date_create(empty($r->timestamps->lastUpdate) ?
          $r->timestamps->created :
          $r->timestamps->lastUpdate), "Y-m-d H:i:s"),
        empty($r->submission_date) ? '' : date_format(date_create($r->submission_date), "Y-m-d H:i:s"),
        t($r->status),
        $r->actions,
        $r->id
      );
    }, $requests);
    return $res;
  }
  return FALSE;
}

function _obiba_mica_data_access_request_profile_attribute($request, $key) {
  if (!empty($request->profile->attributes)) {
    foreach ($request->profile->attributes as $attr) {
      if ($attr->key == $key) {
        return $attr->value;
      }
    }
  }
  return NULL;
}

function _obiba_mica_data_access_request_profile_full_name($request) {
  $full_name = $request->applicant;
  $first_name = _obiba_mica_data_access_request_profile_attribute($request, 'firstName');
  if (!empty($first_name)) {
    $full_name = $first_name;
  }
  $last_name = _obiba_mica_data_access_request_profile_attribute($request, 'lastName');
  if (!empty($last_name)) {
    $full_name = $full_name . ' ' . $last_name;
  }
  $email = _obiba_mica_data_access_request_profile_attribute($request, 'email');
  if (!empty($email)) {
    // cannot do this because it breaks the delete action
    //$full_name = l($full_name, 'mailto:' . $email, array('absolute' => TRUE));
  }
  return $full_name;

}