<?php
/**
 * @file
 * Copyright (c) 2015 OBiBa. All rights reserved.
 *
 * This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Implements hook_menu().
 */
function obiba_mica_app_angular_menu() {
  $external_items = array();
  $external_items += obiba_mica_app_angular_load_external_menus_definitions();

  foreach ($external_items as $key_item => $external_item) {
    $external_items[$key_item]['page callback']
      = 'obiba_mica_app_angular_main_page';
    if (!empty($external_item['module_caller'])) {
      $external_items[$key_item]['page arguments']
        = array($external_item['module_caller']);
    }
  }
  $items = array();

  $items['obiba-angular-app'] = array(
    'page callback' => 'obiba_mica_app_angular_main_page',
    'access callback' => TRUE,
  );

  $items['obiba_mica_app_angular_view_template/%'] = array(
    'page callback' => 'obiba_mica_app_angular_get_angular_template',
    'access callback' => TRUE,
    'page arguments' => array(1),
  );
  $items['obiba_mica_app_angular/translation/%'] = array(
    'page callback' => 'obiba_mica_app_angular_get_angular_translation',
    'page arguments' => array(2),
    'access callback' => TRUE,
  );
  $items['un-authorized-error'] = array(
    'page callback' => 'obiba_mica_app_angular_set_drupal_message_error',
    'access callback' => TRUE,
  );
  return $items + $external_items;
}

/**
 * Implements hook_library().
 */
function obiba_mica_app_angular_library() {
  return obiba_mica_app_angular_load_angular_library();
}

/**
 * Implements hook_library_alter().
 *
 * Angular library compatible with Jquery 1.10
 */
function obiba_mica_app_angular_library_alter(&$javascript, $module) {
  if (($module == 'obiba_mica_app_angular' || $module == 'system')
    && current_path() == 'obiba-angular-app'
  ) {
    $path = drupal_get_path('module', 'jquery_update');
    jquery_update_jquery_replace($javascript, NULL, $path, NULL, '1.10');
  }

}

/**
 * Implements hook_theme().
 */
function obiba_mica_app_angular_theme($existing, $type, $theme, $path) {
  $path_theme = $path . '/templates';
  $path_view_template = $path . '/js/app/views';
  return array(
    'obiba_angular_main' => array(
      'template' => 'obiba_angular_main',
      'path' => $path_theme,
    ),
    'obiba_mica_app_angular_attachment-input-template' => array(
      'template' => 'obiba_mica_app_angular_attachment-input-template',
      'path' => $path_view_template,
    ),
    'obiba_mica_app_angular_attachment-list-template' => array(
      'template' => 'obiba_mica_app_angular_attachment-list-template',
      'path' => $path_view_template,
    ),
  );
}

/**
 * Hook implementation to load the menus rooting of external angular js modules.
 *
 * @return array
 *   An array of path menu loaded on different hook_load_menus() implementation.
 */
function obiba_mica_app_angular_load_external_menus_definitions() {
  $external_items = array();
  foreach (module_implements('load_menus') as $module) {
    $external_loaded_menu = module_invoke($module, 'load_menus');
    if (!empty($external_loaded_menu)) {
      $external_items += $external_loaded_menu;
    }

  }
  return $external_items;
}

/**
 * Hook implementation to load external angular app js.
 */
function obiba_mica_app_angular_load_external_app_js($module_caller = NULL, $weight_js = NULL) {
  foreach (module_implements('get_js') as $key => $module) {
    // Calling all modules implementing hook_hook_name
    // and load its js.
    if ($module_caller == $module) {
      $module = module_invoke($module, 'get_js', $weight_js);
      if (!empty($module)) {
        return TRUE;
      }
    }
  }
  return FALSE;

}

/**
 * Hook implementation to get external modules names to load.
 *
 * @return string
 *   The module name to load on the AngularJs main app in each Drupal module
 *   that use obiba_mica_app_angular module.
 */
function obiba_mica_app_angular_load_ng_module($module_caller) {
  $ng_modules = array();
  foreach (module_implements('get_ng_module_to_load') as $key => $module) {
    // Calling all modules implementing hook_get_ng_module_to_load
    if ($module_caller == $module) {
      $ng_modules[] = module_invoke($module, 'get_ng_module_to_load');
    }
  }
  if (!empty($ng_modules)) {
    return $ng_modules;
  }
  else {
    return FALSE;
  }
}

/**
 * Load Js resources by folder name.
 *
 * Useful to add some custom AngularJs module.
 */
function obiba_mica_app_angular_load_js_by_folder_app($folder = 'app', $weight_js = 10) {
  $module_path = drupal_get_path('module', 'obiba_mica_app_angular');
  $js = file_scan_directory($module_path . '/js/' . $folder, '/.*\.js$/',
    array('key' => 'name'));

  ksort($js);
  foreach ($js as $file_js) {
    drupal_add_js($file_js->uri, array(
      'type' => 'file',
      'scope' => 'footer',
      'weight' => ++$weight_js
    ));
  }
  return $weight_js;
}

/**
 * Load Js resources.
 */
function obiba_mica_app_angular_load_js_resources($module_caller = NULL) {
  obiba_mica_app_angular_load_libraries_resources('obiba_mica_app_angular');
  $weight_js = obiba_mica_app_angular_load_js_by_folder_app('app');
  $weight_js = obiba_mica_app_angular_load_js_by_folder_app('attachment', $weight_js);
  $weight_js = obiba_mica_app_angular_load_js_by_folder_app('file', $weight_js);
  obiba_mica_app_angular_load_external_app_js($module_caller, $weight_js);
  global $user, $language;
  // TODO Add CSRF token required by restWS.
  $authenticated = user_is_logged_in();
  if (module_exists('obiba_agate')) {
    $authenticated = ObibaAgateClient::hasTicket() || user_is_logged_in();
  }
  $js_settings = array(
    'angularjsApp' => array(
      'modules' => obiba_mica_app_angular_load_ng_module($module_caller),
      'requests_url' => MicaClientPathProvider::DATA_ACCESS_LIST,
      'authenticated' => $authenticated,
      /*  'restws_csrf_token' => drupal_get_token('restws'), */
      'user' => $user,
      'locale' => $language->language,
      'show_detailed_stats' => variable_get_value('dataset_detailed_var_stats'),
      'data_access_config' => obiba_mica_app_angular_get_access_config(),
      'obibaSearchOptions' => obiba_mica_app_angular_get_search_config()
    ),
  );

  drupal_add_js($js_settings, 'setting');
}

/**
 * Load resource + template main app.
 *
 * @return string
 *   The template of the main angular app.
 */
function obiba_mica_app_angular_load_template_app($module_caller = NULL, $node_page_id = NULL) {
  $node_rendered = NULL;
  obiba_mica_app_angular_load_js_resources($module_caller);
  if(!empty($node_page_id)){
    $node_rendered = obiba_mica_commons_get_translated_node($node_page_id);
    $node_rendered['#node']->title = '';
  }
  return theme('obiba_angular_main', array('node_page' => $node_rendered,));
}

/**
 * Callback for the main page app.
 *
 * @return string
 *   The template of the AngularJs app.
 */
function obiba_mica_app_angular_main_page($module_caller = NULL) {
  $current_menu_item = menu_get_item(current_path());
  if (!empty($current_menu_item['title'])) {
    drupal_set_title($current_menu_item['title']);
  }
  return obiba_mica_app_angular_load_template_app($module_caller, variable_get($module_caller.'_page'));
}

/**
 * Callback for a service that return  the app template.
 *
 * @return string
 *   The template of the AngularJs app.
 */
function obiba_mica_app_angular_get_angular_template($angular_template) {
  $cached_template = obiba_mica_commons_get_cache('angular-template-cache-' . $angular_template);
  if (!empty($cached_template)) {
    $angular_template = $cached_template;
  }
  else {
    $angular_template = theme($angular_template);
    obiba_mica_commons_set_cache('angular-template-cache-' . $angular_template, $angular_template);
  }
  print $angular_template;
}

/**
 * Callback for service that return translations to angularJs translate module.
 *
 * @return string
 *   The translation string of the AngularJs app.
 */
function obiba_mica_app_angular_get_angular_translation($lang) {
  $cached_translation = obiba_mica_commons_get_cache('translation-' . $lang);
  if (!empty($cached_translation)) {
    $translation = $cached_translation;
  }
  else {
    $mica_config = new MicaConfigResource();
    $translation = $mica_config->getTranslations($lang);
    obiba_mica_commons_set_cache('translation-' . $lang, $translation, 'cache', time() + (60 * 60));
  }

  print $translation;
}

/**
 * Implements hook_Library().
 */
function obiba_mica_app_angular_load_angular_library() {
  $libraries = array();
  $lib_path = libraries_get_path('angular-app');
  // Make sure we have a valid library path before returning library load info.
  if (!empty($lib_path)) {
    $libraries['angular-app'] = array(
      'title' => 'Angular Js + dependencies',
      'website' => 'https://angularjs.org',
      'version' => 'Last Version',
      'js' => array(

        $lib_path . '/jquery-ui/jquery-ui.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path . '/angular/angular.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path
        . '/angular-resource/angular-resource.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path
        . '/angular-bootstrap/ui-bootstrap-tpls.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path
        . '/angular-sanitize/angular-sanitize.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path . '/ng-obiba/dist/ng-obiba.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path . '/ng-obiba-mica/dist/ng-obiba-mica.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path . '/tv4/tv4.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path . '/objectpath/lib/ObjectPath.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path
        . '/angular-schema-form/dist/schema-form.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path
        . '/angular-schema-form/dist/bootstrap-decorator.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path . '/angular-route/angular-route.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path . '/angular-translate/angular-translate.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path . '/angular-ui/build/angular-ui.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path . '/marked/lib/marked.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path . '/angular-marked/dist/angular-marked.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path . '/moment/moment.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path . '/angular-moment/angular-moment.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path . '/angular-strap/dist/angular-strap.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path . '/rql-nodojo/js/rql.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path
        . '/angular-strap/dist/angular-strap.tpl.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path
        . '/angular-schema-form-datetimepicker/schema-form-date-time-picker.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path . '/filesize/lib/filesize.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path
        . '/ng-file-upload/ng-file-upload-all.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path
        . '/angular-recaptcha/release/angular-recaptcha.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path . '/angular-utils-pagination/dirPagination.js'
        => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path . '/angular-ui-select/dist/select.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path . '/angular-google-chart/ng-google-chart.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
      ),
      'css' => array(
        $lib_path . '/ng-obiba/dist/css/ng-obiba.css' => array(),
        $lib_path . '/ng-obiba-mica/dist/css/ng-obiba-mica.css' => array(),
        $lib_path . '/angular-ui-select/dist/select.css' => array(),
      ),
    );
  }
  return $libraries;
}

/**
 * Add angular-app library to a given module.
 *
 * @param string $module_name
 *   The module name to attach angular-app library.
 */
function obiba_mica_app_angular_load_libraries_resources($module_name) {
  if (drupal_get_library($module_name, 'angular-app')) {
    drupal_add_library($module_name, 'angular-app');
  }
  else {
    watchdog($module_name, 'The library angular-app not loaded', array(),
      WATCHDOG_WARNING);
  }
}

/**
 * A callback to an unauthorized Error page.
 *
 * @return bool
 *   A true status.
 */
function obiba_mica_app_angular_set_drupal_message_error() {
  if (!user_is_logged_in()) {
    drupal_set_message(t('Server rejected your request, please make sure you
    are logged in and try again.'), 'error');
  }
  else {
    drupal_set_message(t('You are not authorized to access the page.'), 'error');
  }
  return TRUE;
}

function obiba_mica_app_angular_get_access_config() {
  return array(
    'newRequestButtonCaption' => variable_get_value('access_new_request_button'),
    'documentsSectionTitle' => variable_get_value('access_documents_section_title'),
    'documentsSectionHelpText' => variable_get_value('access_documents_section_help_text'),
    'downloadButtonCaption' => variable_get_value('access_download_button'),
    'commentsEnabled' => variable_get_value('access_comments_enabled'),
    'userListPageTitle' => variable_get_value('user_list_page_title')
  );
}

/**
 * Search Module settings
 */
function obiba_mica_app_angular_get_search_config() {
  $get_array_value = function ($variable) {
    return array_values(array_filter(array_map('trim', explode(',', variable_get_value($variable)))));
  };
  $coverage_group_by_options = array_map(function($coverage_option){
    return !empty($coverage_option)?TRUE:FALSE;
  }, variable_get_value('coverage_group_by'));

  return array(
    'SearchHelpText' => variable_get_value('help_text_search_page'),
    'ClassificationHelpText' => variable_get_value('help_text_harmonization_potential_page'),
    'showSearchBox' => variable_get_value('mica_show_search_box'),
    'showSearchBrowser' => variable_get_value('mica_show_search_browser'),
    'targetTabsOrder' => $get_array_value('mica_target_tabs_order'),
    'showAllFacetedTaxonomies' => false,
    'variableTaxonomiesOrder' =>  array_keys(obiba_mica_commons_taxonomies_filter_array('mica_variable_taxonomies_order')),
    'datasetTaxonomiesOrder' => empty(variable_get_value('mica_dataset_taxonomy_facet')) ? array() : array('Mica_dataset'),
    'studyTaxonomiesOrder' => empty(variable_get_value('mica_study_taxonomy_facet')) ? array() : array('Mica_study'),
    'networkTaxonomiesOrder' => empty(variable_get_value('mica_network_taxonomy_facet')) ? array() : array('Mica_network'),
    'searchTabsOrder' => $get_array_value('mica_search_tabs_order'),
    'resultTabsOrder' => $get_array_value('mica_result_tabs_order'),
    'variables' =>  array(
        'showSearchTab' => variable_get_value('search_variables'),
        'variablesColumn' => array(
          'showVariablesTypeColumn' => variable_get_value('variables_column_type'),
          'showVariablesStudiesColumn' => variable_get_value('variables_column_study'),
          'showVariablesDatasetsColumn' => variable_get_value('variables_column_dataset'),
          'showDatasetsStudiesColumn' => variable_get_value('datasets_column_studies'),
          'showDatasetsVariablesColumn' => variable_get_value('datasets_column_variables'),
        )
      ),
    'datasets' =>
      array(
        'showSearchTab' => variable_get_value('search_datasets'),
        'showDatasetsSearchFilter' => variable_get_value('search_datasets_autocomplete'),
        'datasetsColumn' => array(
          'showDatasetsAcronymColumn' => variable_get_value('datasets_column_acronym'),
          'showDatasetsTypeColumn' => variable_get_value('datasets_column_type'),
          'showDatasetsNetworkColumn' => variable_get_value('datasets_column_networks'),
          'showDatasetsStudiesColumn' => variable_get_value('datasets_column_studies'),
          'showDatasetsVariablesColumn' => variable_get_value('datasets_column_variables'),
        )
      ),
    'studies' =>
      array(
        'showSearchTab' => variable_get_value('search_studies'),
        'showStudiesSearchFilter' => variable_get_value('studies_facet_search'),
        'studiesColumn' => array(
          'showStudiesDesignColumn' => variable_get_value('studies_column_design'),
          'showStudiesQuestionnaireColumn' => variable_get_value('studies_column_questionnaire'),
          'showStudiesPmColumn' => variable_get_value('studies_column_pm'),
          'showStudiesBioColumn' => variable_get_value('studies_column_bio'),
          'showStudiesOtherColumn' => variable_get_value('studies_column_other'),
          'showStudiesParticipantsColumn' => variable_get_value('studies_column_participants'),
          'showStudiesNetworksColumn' => variable_get_value('studies_column_networks'),
          'showStudiesStudyDatasetsColumn' => variable_get_value('studies_column_study_datasets'),
          'showStudiesHarmonizationDatasetsColumn' => variable_get_value('studies_column_harmonization_datasets'),
          'showStudiesVariablesColumn' => variable_get_value('studies_column_variables'),
          'showStudiesStudyVariablesColumn' => variable_get_value('studies_column_study_variables'),
          'showStudiesDataschemaVariablesColumn' => variable_get_value('studies_column_dataschema_variables'),
        )
      ),
    'networks' =>
      array(
        'showSearchTab' => variable_get_value('search_networks'),
        'networksColumn' => array(
          'showNetworksStudiesColumn' => variable_get_value('networks_column_studies'),
          'showNetworksStudyDatasetColumn' => variable_get_value('networks_column_study_datasets'),
          'showNetworksHarmonizationDatasetColumn' => variable_get_value('networks_column_harmonization_datasets'),
          'showNetworksVariablesColumn' => variable_get_value('networks_column_variables'), 
          'showNetworksStudyVariablesColumn' => variable_get_value('networks_column_study_variables'),
          'showNetworksDataschemaVariablesColumn' => variable_get_value('networks_column_dataschema_variables'),
        )
      ),
    'coverage' =>
      array(
        'groupBy' => $coverage_group_by_options,
      ),
  );
}
