<?php
/**
 * @file
 * Copyright (c) 2015 OBiBa. All rights reserved.
 *
 * This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Implements hook_menu().
 */
function obiba_mica_app_angular_menu() {
  $external_items = array();
  $external_items += obiba_mica_app_angular_load_external_menus_definitions();

  foreach ($external_items as $key_item => $external_item) {
    $external_items[$key_item]['page callback']
      = 'obiba_mica_app_angular_main_page';
  }
  $items = array();

  $items['obiba-angular-app'] = array(
    'page callback' => 'obiba_mica_app_angular_main_page',
    'access callback' => TRUE,
  );

  $items['obiba_mica_app_angular/%/%'] = array(
    'page callback' => 'obiba_mica_app_angular_get_angular_template',
    'access callback' => TRUE,
    'page arguments' => array(1, 2),
  );
  $items['obiba_mica_app_angular/translation'] = array(
    'page callback' => 'obiba_mica_app_angular_get_angular_translation',
    'access callback' => TRUE,
  );
  $items['un-authorized-error'] = array(
    'page callback' => 'obiba_mica_app_angular_set_drupal_message_error',
    'access callback' => TRUE,
  );
  return $items + $external_items;
}

/**
 * Implements hook_library().
 */
function obiba_mica_app_angular_library() {
  return obiba_mica_app_angular_load_angular_library();
}

/**
 * Implements hook_library_alter().
 *
 * Angular library compatible with Jquery 1.10
 */
function obiba_mica_app_angular_library_alter(&$javascript, $module) {
  if (($module == 'obiba_mica_app_angular' || $module == 'system')
    && current_path() == 'obiba-angular-app') {
    $path = drupal_get_path('module', 'jquery_update');
    jquery_update_jquery_replace($javascript, NULL, $path, NULL, '1.10');
  }

}

/**
 * Implements hook_theme().
 */
function obiba_mica_app_angular_theme($existing, $type, $theme, $path) {
  $path_theme = $path . '/templates';
  $path_view_template = $path . '/js/app/views';
  return array(
    'obiba_angular_main' => array(
      'template' => 'obiba_angular_main',
      'path' => $path_theme,
    ),
    'obiba_mica_app_angular_attachment-input-template' => array(
      'template' => 'obiba_mica_app_angular_attachment-input-template',
      'path' => $path_view_template,
    ),
    'obiba_mica_app_angular_attachment-list-template' => array(
      'template' => 'obiba_mica_app_angular_attachment-list-template',
      'path' => $path_view_template,
    ),
  );
}

/**
 * Hook implementation to load the menus rooting of external angular js modules.
 *
 * @return array
 *   An array of path menu loaded on different hook_load_menus() implementation.
 */
function obiba_mica_app_angular_load_external_menus_definitions() {
  $external_items = array();
  foreach (module_implements('load_menus') as $module) {
    $external_loaded_menu = module_invoke($module, 'load_menus');
    if (!empty($external_loaded_menu)) {
      $external_items += $external_loaded_menu;
    }

  }
  return $external_items;
}

/**
 * Hook implementation to load external angular app js.
 */
function obiba_mica_app_angular_load_external_app_js() {
  module_invoke_all('get_js');
}

/**
 * Hook implementation to get external modules names to load.
 *
 * @return string
 *   The module name to load on the AngularJs main app in each Drupal module
 *   that use obiba_mica_app_angular module.
 */
function obiba_mica_app_angular_load_ng_module() {
  foreach (module_implements('get_ng_module_to_load') as $key => $module) {
    // Calling all modules implementing hook_hook_name
    // and return the first result.
    $module = module_invoke($module, 'get_ng_module_to_load');
    if (!empty($module)) {
      return $module;
    }
  }
  return FALSE;
}

/**
 * Load Js resources by folder name.
 *
 * Useful to add some custom AngularJs module.
 */
function obiba_mica_app_angular_load_js_by_folder_app($folder = 'app') {
  $module_path = drupal_get_path('module', 'obiba_mica_app_angular');
  $js = file_scan_directory($module_path . '/js/' . $folder, '/.*\.js$/',
    array('key' => 'name'));

  ksort($js);
  foreach ($js as $file_js) {
    drupal_add_js($file_js->uri, array('type' => 'file', 'scope' => 'footer'));
  }
}

/**
 * Load Js resources.
 */
function obiba_mica_app_angular_load_js_resources() {
  obiba_mica_app_angular_load_libraries_resources('obiba_mica_app_angular');
  obiba_mica_app_angular_load_js_by_folder_app();
  obiba_mica_app_angular_load_js_by_folder_app('attachment');
  obiba_mica_app_angular_load_js_by_folder_app('file');
  obiba_mica_app_angular_load_external_app_js();
  global $user, $language;
  // TODO Add CSRF token required by restWS.
  $authenticated = user_is_logged_in();
  if (module_exists('obiba_agate')) {
    $authenticated = ObibaAgateClient::hasTicket() || user_is_logged_in();
  }
  $js_settings = array(
    'angularjsApp' => array(
      'module' => obiba_mica_app_angular_load_ng_module(),
      'requests_url' => MicaClientPathProvider::DATA_ACCESS_LIST,
      'authenticated' => $authenticated,
      /*  'restws_csrf_token' => drupal_get_token('restws'), */
      'user' => $user,
      'locale' => $language->language,
      'show_detailed_stats' => variable_get_value('dataset_detailed_var_stats'),
    ),
  );

  drupal_add_js($js_settings, 'setting');
}

/**
 * Load resource + template main app.
 *
 * @return string
 *   The template of the main angular app.
 */
function obiba_mica_app_angular_load_template_app() {
  obiba_mica_app_angular_load_js_resources();
  return theme('obiba_angular_main');
}

/**
 * Callback for the main page app.
 *
 * @return string
 *   The template of the AngularJs app.
 */
function obiba_mica_app_angular_main_page() {
  $current_menu_item = menu_get_item(current_path());
  if (!empty($current_menu_item['title'])) {
    drupal_set_title($current_menu_item['title']);
  }
  return obiba_mica_app_angular_load_template_app();
}

/**
 * Callback for a service that return  the app template.
 *
 * @return string
 *   The template of the AngularJs app.
 */
function obiba_mica_app_angular_get_angular_template($module, $angular_template) {
  print theme($angular_template);
}

/**
 * Callback for service that return translations to angularJs translate module.
 *
 * @return string
 *   The translation string of the AngularJs app.
 */
function obiba_mica_app_angular_get_angular_translation() {
  global $language;
  print file_get_contents(sprintf('%s/i18n/%s.json', __DIR__,
    $language->language));
}

/**
 * Implements hook_Library().
 */
function obiba_mica_app_angular_load_angular_library() {
  $libraries = array();
  $lib_path_schema_form = libraries_get_path('angular-app');
  // Make sure we have a valid library path before returning library load info.
  if (!empty($lib_path_schema_form)) {
    $libraries['angular-app'] = array(
      'title' => 'Angular Js + dependencies',
      'website' => 'https://angularjs.org',
      'version' => 'Last Version',
      'js' => array(

        $lib_path_schema_form . '/jquery-ui/jquery-ui.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form . '/angular/angular.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form
        . '/angular-resource/angular-resource.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form
        . '/angular-bootstrap/ui-bootstrap-tpls.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form
        . '/angular-sanitize/angular-sanitize.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form . '/tv4/tv4.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form . '/objectpath/lib/ObjectPath.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form
        . '/angular-schema-form/dist/schema-form.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form
        . '/angular-schema-form/dist/bootstrap-decorator.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form . '/angular-route/angular-route.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form . '/angular-translate/angular-translate.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form . '/angular-ui/build/angular-ui.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form . '/marked/lib/marked.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form . '/angular-marked/angular-marked.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form . '/moment/moment.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form . '/angular-moment/angular-moment.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form . '/angular-strap/dist/angular-strap.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form
        . '/angular-strap/dist/angular-strap.tpl.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form
        . '/angular-schema-form-datetimepicker/schema-form-date-time-picker.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form . '/filesize/lib/filesize.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form
        . '/ng-file-upload/ng-file-upload-all.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form . '/ng-obiba/dist/ng-obiba.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form
        . '/angular-recaptcha/release/angular-recaptcha.min.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form . '/angular-utils-pagination/dirPagination.js'
        => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
        $lib_path_schema_form . '/angular-ui-select/dist/select.js' => array(
          'type' => 'file',
          'scope' => 'footer',
        ),
      ),
      'css' => array(
        $lib_path_schema_form . '/ng-obiba/dist/css/ng-obiba.css' => array(),
        $lib_path_schema_form . '/angular-ui-select/dist/select.css' => array(),
      ),
    );
  }
  return $libraries;
}

/**
 * Add angular-app library to a given module.
 *
 * @param string $module_name
 *   The module name to attach angular-app library.
 */
function obiba_mica_app_angular_load_libraries_resources($module_name) {
  if (drupal_get_library($module_name, 'angular-app')) {
    drupal_add_library($module_name, 'angular-app');
  }
  else {
    watchdog($module_name, 'The library angular-app not loaded', array(),
      WATCHDOG_WARNING);
  }
}

/**
 * A callback to an unauthorized Error page.
 *
 * @return bool
 *   A true status.
 */
function obiba_mica_app_angular_set_drupal_message_error() {
  if (!user_is_logged_in()) {
    drupal_set_message(t('Server rejected your request, please make sure you
    are logged in and try again.'), 'error');
  }
  else {
    drupal_set_message(t('You are not authorized to access the page.'), 'error');
  }
  return TRUE;
}
