<?php
/**
 * @file
 * Mica networks file
 */

include_once('obiba_mica_network-page-list.inc');

function obiba_mica_network_menu() {
  $items = array();

  $items['mica/networks'] = array(
    'title' => 'Networks',
    'description' => 'Published networks',
    'page callback' => 'obiba_mica_network_page_list',
    'file' => 'obiba_mica_network-page-list.inc',
    'access callback' => TRUE,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM
  );

  $items['mica/network/%'] = array(
    'title' => 'Mica network detail',
    'page callback' => 'obiba_mica_network_page_detail',
    'file' => 'obiba_mica_network-page-detail.inc',
    'access callback' => TRUE,
    'page arguments' => array(2),
  );

  $items['mica/coverage/network/%'] = array(
    'page callback' => 'obiba_mica_network_page_detail_coverage',
    'file' => 'obiba_mica_network-page-detail.inc',
    'access callback' => TRUE,
    'page arguments' => array(3),
  );

  $items['mica/refresh_list_networks/%/%/%'] = array(
    //'title' => t('AutoComp Menu'),
    'page callback' => 'obiba_mica_network_retrieve_networks',
    'file' => 'obiba_mica_network-page-list.inc',
    'access arguments' => array('access content'),
    'page arguments' => array(2, 3, 4)
  );

  return $items;
}

/**
 * Implements hook_theme().
 *
 * copy '<modules>/obiba_mica_network/templates/'   files in  your customized theme  '<YOUR_THEME>/templates/' path
 * you can modify default display of listed page templates by rearrange block field for example
 * don't forget to clear the theme registry.
 *
 */
function obiba_mica_network_theme($existing, $type, $theme, $path) {
  $path_theme = $path . '/templates';
  return array(
    'obiba_mica_network-detail' => array('template' => 'obiba_mica_network-detail', 'path' => $path_theme),
    'obiba_mica_network_detail_coverage' => array(
      'template' => 'obiba_mica_network_detail_coverage',
      'path' => $path_theme
    ),
    'obiba_mica_network-list' => array('template' => 'obiba_mica_network-list', 'path' => $path_theme),
    'obiba_mica_network-list-page-block' => array(
      'template' => 'obiba_mica_network-list-page-block',
      'path' => $path_theme
    ),
    'obiba_mica_network-charts' => array(
      'template' => 'obiba_mica_network-charts',
      'path' => $path_theme
    ),
  );
}

function obiba_mica_network_networks_list($study_id = NULL) {
  return obiba_mica_network_networks_table(obiba_mica_network_get_networks($study_id, NULL, NULL, NULL));
}

function obiba_mica_network_load_charts_libs() {
  $charts_info = variable_get_value('charts_default_settings');
  if ($charts_info['library'] == 'highcharts') {
    $module_path_ = libraries_get_path('highcharts');
    drupal_add_js($module_path_ . '/js/highcharts.js', 'file');
    drupal_add_js(drupal_get_path('module', 'obiba_mica_commons') . '/js/charts_highcharts.js', 'file');
  }
  else {
    drupal_add_js('https://www.google.com/jsapi', 'external');
    drupal_add_js(drupal_get_path('module', 'obiba_mica_commons') . '/js/charts_google.js', 'file');
  }
}
