<?php
/**
 * @file
 * Mica studies file
 */

function obiba_mica_study_menu() {
  $items = array();

  $items['mica/studies'] = array(
    'title' => 'Studies',
    'description' => 'Published studies',
    'page callback' => 'obiba_mica_study_page_list',
    'file' => 'obiba_mica_study-page-list.inc',
    'access callback' => TRUE,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM
  );

  $items['mica/study/%/coverage'] = array(
    'page callback' => 'obiba_mica_study_page_detail_coverage',
    'file' => 'obiba_mica_study-page-detail.inc',
    'access callback' => TRUE,
    'page arguments' => array(2),
  );

  $items['mica/study/%/networks'] = array(
    'page callback' => 'obiba_mica_study_page_detail_networks',
    'file' => 'obiba_mica_study-page-detail.inc',
    'access callback' => TRUE,
    'page arguments' => array(2),
  );

  $items['mica/study/%/datasets'] = array(
    'page callback' => 'obiba_mica_study_page_detail_datasets',
    'file' => 'obiba_mica_study-page-detail.inc',
    'access callback' => TRUE,
    'page arguments' => array(2),
  );

  $items['mica/study/%'] = array(
    'title' => 'Mica study detail',
    'page callback' => 'obiba_mica_study_page_detail',
    'file' => 'obiba_mica_study-page-detail.inc',
    'access callback' => TRUE,
    'page arguments' => array(2),
  );

  $items['mica/refresh_list_studies/%/%/%/%'] = array(
    //'title' => t('AutoComp Menu'),
    'page callback' => 'obiba_mica_study_retrieve_studies',
    'file' => 'obiba_mica_study-page-list.inc',
    'access arguments' => array('access content'),
    'page arguments' => array(2, 3, 4, 5)
  );

  return $items;
}

/**
 * Implements hook_theme().
 *
 * copy '<modules>/obiba_mica_study/templates/'   files in  yor customized theme  '<YOUR_THEME>/templates/' path
 * you can modify default display of listed page templates by rearrange block field for example
 * don't forget to clear the theme registry.
 *
 */

function obiba_mica_study_theme($existing, $type, $theme, $path) {
  $path_theme = $path . '/templates';
  return array(
    'obiba_mica_study_list-page' => array('template' => 'obiba_mica_study-list-page', 'path' => $path_theme),
    'obiba_mica_study-list-page-block' => array(
      'template' => 'obiba_mica_study-list-page-block',
      'path' => $path_theme
    ),
    'obiba_mica_study_detail' => array('template' => 'obiba_mica_study-detail', 'path' => $path_theme),
    'obiba_mica_study_detail_coverage' => array('template' => 'obiba_mica_study_detail_coverage', 'path' => $path_theme),
    'obiba_mica_study_detail_networks' => array('template' => 'obiba_mica_study_detail_networks', 'path' => $path_theme),
    'obiba_mica_study_detail_datasets' => array('template' => 'obiba_mica_study_detail_datasets', 'path' => $path_theme),
    'mica_population_detail' => array('template' => 'obiba_mica_study-population-detail', 'path' => $path_theme),
    'mica_population_content_detail' => array('template' => 'obiba_mica_study-population-content-detail', 'path' => $path_theme),
    'mica_population_content_detail_modal' => array('template' => 'obiba_mica_study-population-content-detail-modal', 'path' => $path_theme),
    'mica_dce_detail' => array('template' => 'obiba_mica_study-dce-detail', 'path' => $path_theme),
    'mica_contact_detail' => array('template' => 'obiba_mica_study-contact-detail', 'path' => $path_theme),
    'obiba_mica_study_attachments' => array('template' => 'obiba_mica_study_attachments', 'path' => $path_theme),
    'obiba_mica_study_opal' => array('template' => 'obiba_mica_study_opal', 'path' => $path_theme),
    'obiba_mica_study_fixed_sidebar' => array('template' => 'obiba_mica_study_fixed_sidebar', 'path' => $path_theme)
  );
}

/**
 * Implements hook_block_info().
 */
function obiba_mica_study_block_info() {
  $blocks['studies-tab-list'] = array(
    'info' => t('Studies list'),
    'title' => '',
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '*mica/studies',
    'weight' => 3,
    'custom' => 1,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function obiba_mica_study_block_view($delta = '') {
//  switch ($delta) {
//    case 'studies-tab-list' :
//      $output = theme('obiba_mica_study_list', array('list_studies' => obiba_mica_study_get_studies()));
//      $block['subject'] = '';
//      $block['content'] = $output;
//      return $block;
//
//    default:
//      break;
//  }
}

/**
 * @param $gender_val
 *
 * @return text value gender
 */
function obiba_mica_study_get_gender($gender_val) {
  switch ($gender_val) {
    case 0:
      return t('Men only');
    case 1:
      return t('Women only');
  }
}

function obiba_mica_study_get_dce_property($dce, $property, $default) {
  if (isset($dce['data']) && isset($dce['data'][$property])) {
    return $dce['data'][$property];
  }
  if (isset($dce[$property])) {
    return $dce[$property];
  }
  return $default;
}

function obiba_mica_study_sort_dce($x, $y) {
  $x_start = obiba_mica_commons_convert_to_month(
    obiba_mica_study_get_dce_property($x, 'start_year', 0),
    obiba_mica_study_get_dce_property($x, 'start_month', 0));

  $y_start = obiba_mica_commons_convert_to_month(
    obiba_mica_study_get_dce_property($y, 'start_year', 0),
    obiba_mica_study_get_dce_property($y, 'start_month', 0));

  if ($x_start === $y_start) {
    $x_end = obiba_mica_commons_convert_to_month(
      obiba_mica_study_get_dce_property($x, 'end_year', 0),
      obiba_mica_study_get_dce_property($x, 'end_month', 0));

    $y_end = obiba_mica_commons_convert_to_month(
      obiba_mica_study_get_dce_property($y, 'end_year', 0),
      obiba_mica_study_get_dce_property($y, 'end_month', 0));

    if ($x_end === $y_end) {
      $x_created = obiba_mica_study_get_dce_property($x, 'created', 0);
      $y_created = obiba_mica_study_get_dce_property($y, 'created', 0);
      if ($x_created === $y_created) {
        return 0;
      }
      return $x_created < $y_created ? -1 : 1;
    }
    return $x_end < $y_end ? -1 : 1;
  }
  return $x_start < $y_start ? -1 : 1;
}

function obiba_mica_study_get_attachment_url($study_id, $attachment) {
  return sprintf("%s/ws/draft/study/%s/file/%s/_download",
    variable_get('mica_url', 'https://localhost:8445'),
    $study_id,
    $attachment->id);
}

function obiba_mica_study_load_libs() {
  $module_path_ = drupal_get_path('module', 'obiba_mica_commons');
  drupal_add_js($module_path_ . '/js/obiba-mica-commons-affix.js');
  drupal_add_js($module_path_ . '/js/obiba_mica_commons_attachment_download.js');
  drupal_add_js($module_path_ . '/js/obiba-mica-commons-got-top.js');
}

function obiba_mica_study_library_alter(&$libraries, $module) {
  $mica_common_chart_js = drupal_get_path('module', 'obiba_mica_commons');
  drupal_add_js($mica_common_chart_js . '/js/charts_google.js');
}



