<?php

/**
 * Implements hook_menu().
 */
function mica_client_menu() {
  global $user;
  $items = array();

  $items['admin/config/system/obiba'] = array(
    'title' => 'OBiBa Study settings',
    'description' => 'Configure Mica services',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mica_client_admin_settings'),
    'access arguments' => array('administer obiba'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'mica_client.admin.inc',
  );
  return $items;
}