<?php
/**
 * Copyright (c) 2016 OBiBa. All rights reserved.
 *
 * This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
* @file
* Mica studies file
*/

function obiba_mica_lists_menu() {
//  $items = array();

//  $items['mica/studies/list'] = array(
//    'title' => 'Studies',
//    'description' => 'Published studies',
//    'page callback' => 'obiba_mica_lists_page_study_list',
//    'access callback' => 'obiba_mica_study_access_page',
//    'menu_name' => 'main-menu',
//    'type' => MENU_NORMAL_ITEM
//  );
}


/**
 * Implements hook_load_menus().
 */
function obiba_mica_lists_load_menus() {
  $items = array();
  $order = !empty(variable_get_value('study_list_default_order_sort') && variable_get_value('study_list_default_order_sort') == 'desc') ? '-' : '';
  $items[MicaClientPathProvider::PAGE_STUDIES_LIST] =
    array(
      'access callback' => 'obiba_mica_study_access_page',
      'title' => 'Studies List',
      'module_caller' => 'obiba_mica_lists',
      'menu_name' => 'main-menu',
      'weight' => 10,
      'options' => array('fragment' => 'search?query=study(exists(Mica_study.id),sort(' . $order . variable_get_value('study_list_name_acronym_sort') . '))'),
    );
//  $items[MicaClientPathProvider::PAGE_NETWORKS_LIST] =
//    array(
//    'access callback' => 'obiba_mica_study_access_page',
//    'title' => 'Network List',
//    'module_caller' => 'obiba_mica_lists',
//    'menu_name' => 'main-menu',
//    'weight' => 10,
//    'options' => array('fragment' => 'search?query=network(exists(Mica_network.id))'),
//  );
  return $items;
}

/**
 * Implements hook_get_ng_module_to_load().
 */
function obiba_mica_lists_get_ng_module_to_load() {
  switch (current_path()){
    case MicaClientPathProvider::PAGE_STUDIES_LIST:
      obiba_mica_lists_options(MicaClientPathProvider::PAGE_STUDIES_LIST);
      return 'mica.ObibaSearch';
    case MicaClientPathProvider::PAGE_NETWORKS_LIST:
      obiba_mica_lists_options(MicaClientPathProvider::PAGE_NETWORKS_LIST);
      return 'mica.ObibaSearch';
  }
  return FALSE;
}

/**
 * Implements hook_get_js().
 */
function obiba_mica_lists_get_js($weight_js) {
  if (in_array(current_path(), array(MicaClientPathProvider::PAGE_STUDIES_LIST, MicaClientPathProvider::PAGE_NETWORKS_LIST))) {
    $module_path = drupal_get_path('module', 'obiba_mica_lists');
    $js = file_scan_directory($module_path . '/js/app', '/.*\.js$/', array('key' => 'name'));
    ksort($js);
    foreach ($js as $file_js) {
      drupal_add_js($file_js->uri, array(
        'type' => 'file',
        'scope' => 'footer',
        'weight' => ++$weight_js,
      ));
    }
  }
  return ++$weight_js;
}



/**
 * Load list search options
 */
function obiba_mica_lists_options($current_path){
  $study_facet = NULL;
  $network_facet = array();
  $dataset_facet = NULL;
  $result_tabs_order = NULL;
  $target_tabs_order = NULL;
  $studies_options = array();
  switch ($current_path){
    case MicaClientPathProvider::PAGE_STUDIES_LIST:
      $study_facet = 'Mica_study';
      $result_tabs_order = array('study');
      $target_tabs_order = array('study');
      $studies_options = array(
        'studiesListOptions' => array(
          'studiesCountCaption' => variable_get_value('studies_list_show_studies_count_caption'),
          'studiesSearchForm' => variable_get_value('studies_list_show_search_form'),
          'studiesSupplInfoDetails' => variable_get_value('studies_list_show_study_sup_info'),
          'studiesTrimedDescrition' => variable_get_value('studies_list_show_trimmed_description_study'),
          'sortField' => array(
            'options' => array(
              array(
                'value' => 'name',
                'label' => 'name'
              ),
              array(
                'value' => 'acronym',
                'label' => 'acronym'
              ),
              array(
                'value' => 'numberOfParticipants-participant-number',
                'label' => 'study_taxonomy.vocabulary.numberOfParticipants-participant-number.title'
              )
            ),
            'default' => variable_get_value('study_list_name_acronym_sort'),
          ),
          'orderField' => array(
            'options' => array(
              array(
                'value' => '',
                'label' => 'asc'
              ),
              array(
                'value' => '-',
                'label' => 'desc'
              )
            ),
            'default' => variable_get_value('study_list_default_order_sort')
          )
        ),
      );
      break;
    case MicaClientPathProvider::PAGE_NETWORKS_LIST:
      $network_facet = 'Mica_network';
      $result_tabs_order = array('network');
      $target_tabs_order = array('network');
      break;

  }
  drupal_add_js(array(
    'obibaListOptions' => array(
      'studyTaxonomiesOrder' => array($study_facet),
      'networkTaxonomiesOrder' => array($network_facet),
      'datasetTaxonomiesOrder' => array(),
      'dataset' => array('showSearchTab' => 0),
      'networks' => array('showSearchTab' => 1),
      'resultTabsOrder' => $result_tabs_order,
      'searchTabsOrder' => array('list'),
      'showSearchBox' => 0,
      'showSearchBrowser' => 0,
      'studies' => $studies_options,
      'targetTabsOrder' => $target_tabs_order,
      'variableTaxonomiesOrder' => array(),
      'variables' => array('showSearchTab')
    ),
  ),
    'setting')
  ;
}

/**
 * Implements hook_theme().
 */
function obiba_mica_lists_theme($existing, $type, $theme, $path) {
  //$path_theme = $path . '/templates';
  $path_views_theme = $path . '/js/app/views';
  $path_component_theme = $path. '/js/app/component';
  return array(
    'list-sort-widget-template' => array(
      'template' => 'list-sort-widget-template',
      'path' => $path_component_theme . '/sort-widget'
    ),
    'list-search-widget-template' => array(
      'template' => 'list-search-widget-template',
      'path' => $path_component_theme . '/input-search-widget'
    ),
    'studies-search-result-table-template' => array(
      'template' => 'studies-search-result-table-template',
      'path' => $path_views_theme . '/list'
    ),
    'search-result-list-template' => array(
      'template' => 'search-result-list-template',
      'path' => $path_views_theme
    )
  );

}
