<?php
/**
 * Copyright (c) 2016 OBiBa. All rights reserved.
 *
 * This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
* @file
* Mica studies file
*/

define("ANGULAR_LIST_STUDIES", 'mica/list/study');
define("ANGULAR_LIST_INDIVIDUAL_STUDIES", 'mica/list/study' . '/' .  DrupalMicaStudyResource::INDIVIDUAL_STUDY);
define("ANGULAR_LIST_HARMONIZATION_STUDIES", 'mica/list/study' . '/' .  DrupalMicaStudyResource::HARMONIZATION_STUDY);
define("ANGULAR_LIST_NETWORKS", 'mica/list/network');

function obiba_mica_lists_menu() {
  $items['admin/config/obiba-mica/obiba-mica-list-settings'] = array(
    'title' => 'Obiba Mica Lists Settings',
    'description' => 'Configure Obiba Mica Lists',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('obiba_mica_lists_admin_settings'),
    'access arguments' => array('administer obiba mica'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'obiba_mica_lists.admin.inc',
    'weight' => 6,
  );
  return $items;
}

function obiba_mica_lists_paths(){
  $study_order = !empty(variable_get_value('study_list_default_order_sort') && variable_get_value('study_list_default_order_sort') == 'desc') ? '-' : '';
  $network_order = !empty(variable_get_value('network_list_default_order_sort') && variable_get_value('network_list_default_order_sort') == 'desc') ? '-' : '';
  return array(
    ANGULAR_LIST_STUDIES => array(
      'access callback' => 'obiba_mica_study_access_page',
      'title' => 'Studies List',
      'module_caller' => 'obiba_mica_lists',
      'menu_name' => 'main-menu',
      'weight' => 10,
      'options' => array('fragment' => 'search?query=study(exists(Mica_study.id),sort(' . $study_order . variable_get_value('study_list_name_acronym_sort') . '))'),
      ),
    ANGULAR_LIST_INDIVIDUAL_STUDIES => array(
      'access callback' => 'obiba_mica_study_access_page',
      'title' => 'Individual Studies',
      'module_caller' => 'obiba_mica_lists',
      'menu_name' => 'main-menu',
      'weight' => 10,
      'options' => array('fragment' => 'search?query=study(in(Mica_study.className,Study),sort(' . $study_order . variable_get_value('study_list_name_acronym_sort') . '))'),
    ),
    ANGULAR_LIST_HARMONIZATION_STUDIES => array(
      'access callback' => 'obiba_mica_study_access_page',
      'title' => 'Harmonization Studies',
      'module_caller' => 'obiba_mica_lists',
      'menu_name' => 'main-menu',
      'weight' => 10,
      'options' => array('fragment' => 'search?query=study(in(Mica_study.className,HarmonizationStudy),sort(' . $study_order . variable_get_value('study_list_name_acronym_sort') . '))'),
    ),
    ANGULAR_LIST_NETWORKS => array(
      'access callback' => 'obiba_mica_study_access_page',
      'title' => 'Networks',
      'module_caller' => 'obiba_mica_lists',
      'menu_name' => 'main-menu',
      'weight' => 10,
      'options' => array('fragment' => 'search?query=network(exists(Mica_network.id),sort(' . $network_order . variable_get_value('network_list_default_field_sort') . '))'),
    ),
  );
}
/**
 * Implements hook_load_menus().
 */
function obiba_mica_lists_load_menus() {
  return obiba_mica_lists_paths();
}

/**
 * Implements hook_get_ng_module_to_load().
 */
function obiba_mica_lists_get_ng_module_to_load() {
  if (obiba_mica_lists_options(current_path())) {
    return 'mica.ObibaSearch';
  }
  return FALSE;
}

/**
 * Implements hook_get_js().
 */
function obiba_mica_lists_get_js($weight_js) {
  if (in_array(current_path(), array(
    ANGULAR_LIST_STUDIES,
    ANGULAR_LIST_INDIVIDUAL_STUDIES,
    ANGULAR_LIST_HARMONIZATION_STUDIES,
    ANGULAR_LIST_NETWORKS
  ))) {
    $module_path = drupal_get_path('module', 'obiba_mica_lists');
    $js = file_scan_directory($module_path . '/js/app', '/.*\.js$/', array('key' => 'name'));
    ksort($js);
    foreach ($js as $file_js) {
      drupal_add_js($file_js->uri, array(
        'type' => 'file',
        'scope' => 'footer',
        'weight' => ++$weight_js,
      ));
    }
  }
  return ++$weight_js;
}

/*
 * Networks list options
 */
function obiba_mica_lists_networks_options(){
  $acronym_name_sort = variable_get_value('network_list_default_field_sort');
  $networks_options = array(
    'fields' =>  array("studyIds", "acronym.*", "name.*", "description.*", "logo"),
    'optionsCols' => array(
      'showNetworksStudiesColumn' => variable_get_value('networks_column_studies'),
      'showNetworksStudyDatasetColumn' => variable_get_value('networks_column_study_datasets'),
      'showNetworksHarmonizationDatasetColumn' => variable_get_value('networks_column_harmonization_datasets'),
      'showNetworksVariablesColumn'  => variable_get_value('networks_column_variables'),
      'showNetworksStudyVariablesColumn'  => variable_get_value('networks_column_study_variables'),
      'showNetworksDataschemaVariablesColumn'  => variable_get_value('networks_column_dataschema_variables'),
      'sortField' => array(
        'options' => array(
          array(
            'value' => 'name',
            'label' => 'name'
          ),
          array(
            'value' => 'acronym',
            'label' => 'acronym'
          ),
          array(
            'value' => 'numberOfStudies',
            'label' => 'studies'
          ),
        ),
        'default' => $acronym_name_sort,
      ),
      'orderField' => array(
        'options' => array(
          array(
            'value' => '',
            'label' => 'asc'
          ),
          array(
            'value' => '-',
            'label' => 'desc'
          )
        ),
        'default' => variable_get_value('network_list_default_order_sort')
      )
    ),
  );
return $networks_options;
}

/*
 * Studies list options
 */
function obiba_mica_lists_studies_options($current_path){
  $acronym_name_sort = variable_get_value('study_list_name_acronym_sort');
  $studies_options = array(
    'fields' =>  array("logo", "objectives.*", "acronym.*", "name.*", "model.methods.design", "model.numberOfParticipants.participant"),
    'studiesListOptions' => array(
      'studiesCountCaption' => variable_get_value('studies_list_show_studies_count_caption'),
      'studiesSearchForm' => variable_get_value('studies_list_show_search_form'),
      'studiesSupplInfoDetails' => variable_get_value('studies_list_show_study_sup_info'),
      'studiesTrimedDescrition' => variable_get_value('studies_list_show_trimmed_description_study'),
      'sortField' => array(
        'options' => array(
          array(
            'value' => 'name',
            'label' => 'name'
          ),
          array(
            'value' => 'acronym',
            'label' => 'acronym'
          ),
          array(
            'value' => 'numberOfParticipants-participant-number',
            'label' => 'study_taxonomy.vocabulary.numberOfParticipants-participant-number.title'
          )
        ),
        'default' => $acronym_name_sort,
      ),
      'orderField' => array(
        'options' => array(
          array(
            'value' => '',
            'label' => 'asc'
          ),
          array(
            'value' => '-',
            'label' => 'desc'
          )
        ),
        'default' => variable_get_value('study_list_default_order_sort')
      )
    ),
  );
  if($current_path === ANGULAR_LIST_HARMONIZATION_STUDIES){
    unset($studies_options['studiesListOptions']['sortField']['options'][2]);
  }
  return $studies_options;
}
/**
 * Load list search options
 */
function obiba_mica_lists_options($current_path){
  $study_facet = NULL;
  $network_facet = array();
  $dataset_facet = NULL;
  $result_tabs_order = NULL;
  $target_tabs_order = NULL;
  $studies_options = array();
  $networks_options = array();
  switch ($current_path){
    case ANGULAR_LIST_STUDIES:
    case ANGULAR_LIST_INDIVIDUAL_STUDIES:
    case ANGULAR_LIST_HARMONIZATION_STUDIES:
      $study_facet = !empty(variable_get_value('obiba_mica_lists_display_study_facets')) ? 'Mica_study' : NULL;
      $result_tabs_order = array('study');
      $target_tabs_order = array('study');
      $studies_options = obiba_mica_lists_studies_options($current_path);
      break;
    case ANGULAR_LIST_NETWORKS:
      $network_facet = !empty(variable_get_value('obiba_mica_lists_display_network_facets')) ? 'Mica_network' : NULL;
      $result_tabs_order = array('network');
      $target_tabs_order = array('network');
      $networks_options = obiba_mica_lists_networks_options();
      break;
    default:
      return FALSE;
  }
  drupal_add_js(array(
    'obibaListOptions' => array(
      'studyTaxonomiesOrder' => array($study_facet),
      'networkTaxonomiesOrder' => array($network_facet),
      'datasetTaxonomiesOrder' => array(),
      'dataset' => array('showSearchTab' => 0),
      'networks' => $networks_options,
      'resultTabsOrder' => $result_tabs_order,
      'searchTabsOrder' => array('list'),
      'showSearchBox' => 0,
      'showSearchBrowser' => 0,
      'studies' => $studies_options,
      'targetTabsOrder' => $target_tabs_order,
      'variableTaxonomiesOrder' => array(),
      'variables' => array('showSearchTab')
    ),
  ),
    'setting');
  $module_path = drupal_get_path('module', 'obiba_mica_lists');
  drupal_add_css($module_path . '/js/app/views/css/input-search-widget.css');
  Return TRUE;
}

/**
 * Implements hook_theme().
 */
function obiba_mica_lists_theme($existing, $type, $theme, $path) {
  //$path_theme = $path . '/templates';
  $path_views_theme = $path . '/js/app/views';
  $path_component_theme = $path. '/js/app/component';
  return array(
    'list-sort-widget-template' => array(
      'template' => 'list-sort-widget-template',
      'path' => $path_component_theme . '/sort-widget'
    ),
    'list-search-widget-template' => array(
      'template' => 'list-search-widget-template',
      'path' => $path_component_theme . '/input-search-widget'
    ),
    'studies-search-result-table-template' => array(
      'template' => 'studies-search-result-table-template',
      'path' => $path_views_theme . '/list'
    ),
    'networks-search-result-table-template' => array(
      'template' => 'networks-search-result-table-template',
      'path' => $path_views_theme . '/list'
    ),
    'search-result-list-template' => array(
      'template' => 'search-result-list-template',
      'path' => $path_views_theme
    )
  );

}
