<?php

function mica_client_network_install() {
  mica_client_network_create_node();
}

function mica_client_network_create_node() {
  $my_body_content = '<div> <p>This page displays the list of study consortia. Each study consortia is described in a same standard way that can be easily customized to reflect consortium specificities.</p> </div> <hr/>';
  $node_page = mica_client_commons_add_page(st('Networks'), st($my_body_content));
  variable_set('networks_page', $node_page->nid);
}