<?php
/**
 * @file
 * Mica networks file
 */

function mica_client_network_menu() {
  $items = array();

  $items['mica/networks'] = array(
    'title' => t('Networks'),
    'description' => t('Published networks'),
    'page callback' => 'mica_client_network_page_list',
    'file' => 'mica_client_network-page-list.inc',
    'access callback' => TRUE,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM
  );

  $items['mica/network/%'] = array(
    'title' => t('Mica network detail'),
    'page callback' => 'mica_client_network_page_detail',
    'file' => 'mica_client_network-page-detail.inc',
    'access callback' => TRUE,
    'page arguments' => array(2),
  );
  return $items;
}

/**
 * Implements hook_theme().
 *
 * copy '<modules>/mica_client_network/templates/'   files in  your customized theme  '<YOUR_THEME>/templates/' path
 * you can modify default display of listed page templates by rearrange block field for example
 * don't forget to clear the theme registry.
 *
 */
function mica_client_network_theme($existing, $type, $theme, $path) {
  $path_theme = $path . '/templates';
  return array(
    'mica_client_network-detail' => array('template' => 'mica_client_network-detail', 'path' => $path_theme),
  );
}