<?php
/**
 * @file
 * Mica studies file
 */


function mica_client_study_menu() {
  $items = array();

  $items['mica/studies'] = array(
    'title' => t('Studies'),
    'description' => t('Published studies'),
    'page callback' => 'mica_client_study_page_list',
    'file' => 'mica_client_study-page-list.inc',
    'access callback' => TRUE,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM
  );

  $items['mica/studies_search/%'] = array(
    'title' => t('Studies Search'),
    'description' => t('Search published studies'),
    'page callback' => 'mica_client_study_page_search',
    'file' => 'mica_client_study-page-search.inc',
    'access callback' => TRUE,
    'page arguments' => array(2)
  );

  $items['mica/study/%'] = array(
    'title' => t('Mica study detail'),
    'page callback' => 'mica_client_study_page_detail',
    'file' => 'mica_client_study-page-detail.inc',
    'access callback' => TRUE,
    'page arguments' => array(3),
  );
  return $items;
}

function mica_client_study_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  $links = array();
  switch ($root_path) {
    case 'mica/studies':
      $links['mica/studies_search'] = array(
        '#weight' => 30,
        '#theme' => 'menu_local_action',
        '#link' => array(
          'title' => t('Studies Search'),
          'href' => 'mica/studies_search/_all',
          'localized_options' => array(
//                  'query' => array(
//                    'f[0]' => 'search_api_combined_1:' . $node->nid
//                  ),
            'attributes' => array(
              'class' => 'highlight',
            ),
          ),
        ),
      );

      break;
  }

  $data['actions']['output'] = array_merge($data['actions']['output'], $links);
}

/**
 * Implements hook_requirements().
 */

//function mica_client_study_requirements($phase) {
//  $requirements = array();
//  // Ensure translations do not break at install time
//  $t = get_t();
//  $requirements['micatimelines'] = array(
//    'title' => $t('Time lines  Library'),
//  );
//  $libraries = libraries_get_libraries();
//  if (isset($libraries['micatimelines'])) {
//    $requirements['micatimelines']['value'] = $t('Installed');
//    $requirements['micatimelines']['severity'] = REQUIREMENT_OK;
//  }
//  else {
//    $requirements['micatimelines']['value'] = $t('Not Installed');
//    $requirements['micatimelines']['severity'] = REQUIREMENT_ERROR;
//    $requirements['micatimelines']['description'] = $t('Please install the the time lines library %url.', array('%url' => 'http://obiba.org.com'));
//  }
//
//  return $requirements;
//}

/**
 * Implements hook_theme().
 */
function mica_client_study_theme($existing, $type, $theme, $path) {
  $path_theme = drupal_get_path('module', 'mica_client_study') . '/templates';
  return array(
    'mica_client_study_list' => array('template' => 'mica_client_study-list', 'path' => $path_theme),
    'mica_client_study_search' => array('template' => 'mica_client_study-search', 'path' => $path_theme),
    'mica_client_study_detail' => array('template' => 'mica_client_study-detail', 'path' => $path_theme),
    'mica_population_detail' => array('template' => 'mica_client_study-population-detail', 'path' => $path_theme),
    'mica_dce_detail' => array('template' => 'mica_client_study-dce-detail', 'path' => $path_theme),
    'mica_client_study_attachments' => array('template' => 'mica_client_study_attachments', 'path' => $path_theme),
    'mica_client_study_block_search' => array('template' => 'mica_client_study_block_search', 'path' => $path_theme)
  );
}

/**
 * @param $gender_val
 *
 * @return text value gender
 */
function mica_client_study_get_gender($gender_val) {
  switch ($gender_val) {
    case 0:
      return t('Men');
    case 1:
      return t('Women');
  }
}

function mica_client_study_get_dce_property($dce, $property, $default) {
  if (isset($dce['data']) && isset($dce['data'][$property])) {
    return $dce['data'][$property];
  }
  if (isset($dce[$property])) {
    return $dce[$property];
  }
  return $default;
}

function mica_client_study_sort_dce($x, $y) {
  $x_start = mica_client_commons_convert_to_month(
    mica_client_study_get_dce_property($x, 'start_year', 0),
    mica_client_study_get_dce_property($x, 'start_month', 0));

  $y_start = mica_client_commons_convert_to_month(
    mica_client_study_get_dce_property($y, 'start_year', 0),
    mica_client_study_get_dce_property($y, 'start_month', 0));

  if ($x_start === $y_start) {
    $x_end = mica_client_commons_convert_to_month(
      mica_client_study_get_dce_property($x, 'end_year', 0),
      mica_client_study_get_dce_property($x, 'end_month', 0));

    $y_end = mica_client_commons_convert_to_month(
      mica_client_study_get_dce_property($y, 'end_year', 0),
      mica_client_study_get_dce_property($y, 'end_month', 0));

    if ($x_end === $y_end) {
      $x_created = mica_client_study_get_dce_property($x, 'created', 0);
      $y_created = mica_client_study_get_dce_property($y, 'created', 0);
      if ($x_created === $y_created) {
        return 0;
      }
      return $x_created < $y_created ? -1 : 1;
    }
    return $x_end < $y_end ? -1 : 1;
  }
  return $x_start < $y_start ? -1 : 1;
}

function mica_client_study_get_attachment_url($study_id, $attachment) {
  return sprintf("%s/ws/draft/study/%s/file/%s/_download",
    variable_get('mica_url', 'https://localhost:8445'),
    $study_id,
    $attachment->id);
}

/**
 * Implements hook_block_info().
 */
function mica_client_study_block_info() {
  $blocks['search-access'] = array(
    'info' => 'Facet search Data access',
    'title' => 'DATA ACCESS',
    'status' => 1,
    'region' => 'primary',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '*mica/studies/_search*',
    'weight' => 50,
    'custom' => 1,
  );

  $blocks['search-methods-designs'] = array(
    'info' => 'Facet search Study Design',
    'title' => 'STUDY DESIGN',
    'status' => 1,
    'region' => 'primary',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '*mica/studies/_search*',
    'weight' => 49,
    'custom' => 1,
  );

  $blocks['search-methods-recruitments'] = array(
    'info' => 'Facet search Recruitmenet target',
    'title' => 'RECRUITMENT TARGET',
    'status' => 1,
    'region' => 'primary',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '*mica/studies/_search*',
    'weight' => 49,
    'custom' => 1,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function mica_client_study_block_view($delta = '') {
  switch ($delta) {
    case 'search-access':
      if (user_access('access content')) { //good idea to check user perms here
        $block['subject'] = t('DATA ACCESS');
        $block['content'] = mica_client_study_precess_block_theme($delta);
      }
      return $block;

    case 'search-methods-designs':
      if (user_access('access content')) { //good idea to check user perms here
        $block['subject'] = t('STUDY DESIGN');
        $block['content'] = mica_client_study_precess_block_theme($delta);
      }
      return $block;

    case 'search-methods-recruitments':
      if (user_access('access content')) { //good idea to check user perms here
        $block['subject'] = t('RECRUITMENT TARGET');
        $block['content'] = mica_client_study_precess_block_theme($delta);
      }
      return $block;

  }
}

function mica_client_study_precess_block_theme($block_delta) {
  $items = array();
  $agregation_facet = NULL;
  if (!empty($block_delta)) {
    $agregation_facet = key(mica_client_study_get_dto_facet_aggs($block_delta));
    foreach (current(mica_client_study_get_dto_facet_aggs($block_delta)) as $term) {
      ;
      $items[$term->key] = array(
        '#markup' => '<div id="checkthebox" class="terms_checkbox"><input type="checkbox" name="' .
          $agregation_facet . '[]" value="' . $agregation_facet . '.' . $term->key . '" id="' .
          $agregation_facet . '-' . $term->key . '" >' .
          //  '<a href="#"  disabled="disabled" id="checkthebox" term="'. $agregation_facet . '-' . $term->key.'" >'.
          $term->key . '(' . $term->count . ') </div>'
      );
    }
  }
  return theme('mica_client_study_block_search', array('items' => $items, 'formId' => $agregation_facet));
}

function mica_client_study_get_dto_facet_aggs($tab_block) {
  foreach ($_SESSION['aggregations'] as $facet) {
    if ($facet->aggregation == 'access') {
      $facet_build['search-access']['access'] = $facet->termsAggregations;
    }
    if ($facet->aggregation == 'methods-designs') {
      $facet_build['search-methods-designs']['methods-designs'] = $facet->termsAggregations;
    }
    if ($facet->aggregation == 'methods-recruitments') {
      $facet_build['search-methods-recruitments']['methods-recruitments'] = $facet->termsAggregations;
    }
  }
  return $facet_build[$tab_block];
}



