<?php
/**
 * @file
 * Mica studies file
 */

function mica_client_study_menu() {
  $items = array();

  $items['mica/studies'] = array(
    'title' => t('Studies'),
    'description' => t('Published studies'),
    'page callback' => 'mica_client_study_page_list',
    'file' => 'mica_client_study-page-list.inc',
    'access callback' => TRUE,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM
  );

  $items['mica/study/%'] = array(
    'title' => t('Mica study detail'),
    'page callback' => 'mica_client_study_page_detail',
    'file' => 'mica_client_study-page-detail.inc',
    'access callback' => TRUE,
    'page arguments' => array(2),
  );

  $items['mica/refresh_list_studies/%/%/%'] = array(
    //'title' => t('AutoComp Menu'),
    'page callback' => 'mica_client_study_retrieve_studies',
    'file' => 'mica_client_study-page-list.inc',
    'access arguments' => array('access content'),
    'page arguments' => array(2, 3, 4)
  );

  return $items;
}

/**
 * Implements hook_theme().
 *
 * copy '<modules>/mica_client_study/templates/'   files in  yor customized theme  '<YOUR_THEME>/templates/' path
 * you can modify default display of listed page templates by rearrange block field for example
 * don't forget to clear the theme registry.
 *
 */

function mica_client_study_theme($existing, $type, $theme, $path) {
  $path_theme = $path . '/templates';
  return array(
    'mica_client_study_list-page' => array('template' => 'mica_client_study-list-page', 'path' => $path_theme),
    'mica_client_study-list-page-block' => array(
      'template' => 'mica_client_study-list-page-block',
      'path' => $path_theme
    ),
    'mica_client_study_detail' => array('template' => 'mica_client_study-detail', 'path' => $path_theme),
    'mica_population_detail' => array('template' => 'mica_client_study-population-detail', 'path' => $path_theme),
    'mica_dce_detail' => array('template' => 'mica_client_study-dce-detail', 'path' => $path_theme),
    'mica_client_study_attachments' => array('template' => 'mica_client_study_attachments', 'path' => $path_theme),
    'mica_client_study_opal' => array('template' => 'mica_client_study_opal', 'path' => $path_theme)
  );
}

/**
 * Implements hook_block_info().
 */
function mica_client_study_block_info() {
  $blocks['studies-tab-list'] = array(
    'info' => t('Studies list'),
    'title' => '',
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '*mica/studies',
    'weight' => 3,
    'custom' => 1,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function mica_client_study_block_view($delta = '') {
//  switch ($delta) {
//    case 'studies-tab-list' :
//      $output = theme('mica_client_study_list', array('list_studies' => mica_client_study_get_studies()));
//      $block['subject'] = '';
//      $block['content'] = $output;
//      return $block;
//
//    default:
//      break;
//  }
}

/**
 * @param $gender_val
 *
 * @return text value gender
 */
function mica_client_study_get_gender($gender_val) {
  switch ($gender_val) {
    case 0:
      return t('Men');
    case 1:
      return t('Women');
  }
}

function mica_client_study_get_dce_property($dce, $property, $default) {
  if (isset($dce['data']) && isset($dce['data'][$property])) {
    return $dce['data'][$property];
  }
  if (isset($dce[$property])) {
    return $dce[$property];
  }
  return $default;
}

function mica_client_study_sort_dce($x, $y) {
  $x_start = mica_client_commons_convert_to_month(
    mica_client_study_get_dce_property($x, 'start_year', 0),
    mica_client_study_get_dce_property($x, 'start_month', 0));

  $y_start = mica_client_commons_convert_to_month(
    mica_client_study_get_dce_property($y, 'start_year', 0),
    mica_client_study_get_dce_property($y, 'start_month', 0));

  if ($x_start === $y_start) {
    $x_end = mica_client_commons_convert_to_month(
      mica_client_study_get_dce_property($x, 'end_year', 0),
      mica_client_study_get_dce_property($x, 'end_month', 0));

    $y_end = mica_client_commons_convert_to_month(
      mica_client_study_get_dce_property($y, 'end_year', 0),
      mica_client_study_get_dce_property($y, 'end_month', 0));

    if ($x_end === $y_end) {
      $x_created = mica_client_study_get_dce_property($x, 'created', 0);
      $y_created = mica_client_study_get_dce_property($y, 'created', 0);
      if ($x_created === $y_created) {
        return 0;
      }
      return $x_created < $y_created ? -1 : 1;
    }
    return $x_end < $y_end ? -1 : 1;
  }
  return $x_start < $y_start ? -1 : 1;
}

function mica_client_study_get_attachment_url($study_id, $attachment) {
  return sprintf("%s/ws/draft/study/%s/file/%s/_download",
    variable_get('mica_url', 'https://localhost:8445'),
    $study_id,
    $attachment->id);
}




