<?php
/**
 * @file
 * Mica networks file
 */

include_once('mica_obiba_network-page-list.inc');

function mica_obiba_network_menu() {
  $items = array();

  $items['mica/networks'] = array(
    'title' => t('Networks'),
    'description' => t('Published networks'),
    'page callback' => 'mica_obiba_network_page_list',
    'file' => 'mica_obiba_network-page-list.inc',
    'access callback' => TRUE,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM
  );

  $items['mica/network/%'] = array(
    'title' => t('Mica network detail'),
    'page callback' => 'mica_obiba_network_page_detail',
    'file' => 'mica_obiba_network-page-detail.inc',
    'access callback' => TRUE,
    'page arguments' => array(2),
  );

  $items['mica/refresh_list_networks/%/%/%'] = array(
    //'title' => t('AutoComp Menu'),
    'page callback' => 'mica_obiba_network_retrieve_networks',
    'file' => 'mica_obiba_network-page-list.inc',
    'access arguments' => array('access content'),
    'page arguments' => array(2, 3, 4)
  );

  return $items;
}

/**
 * Implements hook_theme().
 *
 * copy '<modules>/mica_obiba_network/templates/'   files in  your customized theme  '<YOUR_THEME>/templates/' path
 * you can modify default display of listed page templates by rearrange block field for example
 * don't forget to clear the theme registry.
 *
 */
function mica_obiba_network_theme($existing, $type, $theme, $path) {
  $path_theme = $path . '/templates';
  return array(
    'mica_obiba_network-detail' => array('template' => 'mica_obiba_network-detail', 'path' => $path_theme),
    'mica_obiba_network-list' => array('template' => 'mica_obiba_network-list', 'path' => $path_theme),
    'mica_obiba_network-list-page-block' => array(
      'template' => 'mica_obiba_network-list-page-block',
      'path' => $path_theme
    ),
  );
}

function mica_obiba_network_networks_list($study_id = NULL) {
  return mica_obiba_network_networks_table(mica_obiba_network_get_networks($study_id, NULL, NULL, NULL));
}