<?php
/**
 * @file
 * Mica Persons module file
 */

/**
 * Implements hook_menu().
 */
function obiba_mica_persons_menu() {
  $items = array();

  $items['admin/config/obiba-mica/obiba-mica-persons-settings'] = array(
    'title' => 'Persons module settings',
    'description' => 'Configure Persons modules pages',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('obiba_mica_persons_admin_settings'),
    'access arguments' => array('administer obiba mica'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'obiba_mica_persons.admin.inc',
    'weight' => 3,
  );

  $items[MicaClientPersonsPathProvider::PERSONS . '%/ws'] = array(
    'page callback' => 'obiba_mica_persons_list',
    'page arguments' => array(2),
    'file' => 'obiba_mica_persons_service.inc',
    'access callback' => TRUE,
  );

  $items[MicaClientPersonsPathProvider::PERSONS . '%/download/ws'] = array(
    'page callback' => 'obiba_mica_persons_list_csv_download',
    'page arguments' => array(2),
    'file' => 'obiba_mica_persons_service.inc',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function obiba_mica_persons_theme($existing, $type, $theme, $path) {
  $path_theme = $path . '/templates';

  return array(
    'obiba_mica_persons-table' => array(
      'template' => 'obiba_mica_persons-table',
      'path' => $path_theme,
    ),
    'obiba_mica_persons-modal' => array(
      'template' => 'obiba_mica_persons-modal',
      'path' => $path_theme,
    ),
    'obiba_mica_persons-button' => array(
      'template' => 'obiba_mica_persons-button',
      'path' => $path_theme,
    ),
    'mica_person_detail' => array(
      'template' => 'obiba_mica_persons-modal-person-detail',
      'path' => $path_theme
    ),
  );
}

/**
 * Initialize the associated persons dataTables.
 */
function obiba_mica_persons_datatable_init($studies_id) {
  global $language;
  $current_lang = $language->language;
  drupal_add_js(drupal_get_path('module', 'obiba_mica_persons') . '/js/obiba_mica_persons_datatable_init.js',
    array('type' => 'file', 'weight' => 99));
  drupal_add_js(array(
    'resourcePathPersons' => MicaClientPersonsPathProvider::PERSONS,
    'table_header' => obiba_mica_persons_table_headers(),
    'studies_id' => implode(' ', $studies_id),
    'current_lang' => $current_lang,
  ), 'setting');
}

/**
 * Initialize the header persons dataTables.
 */
function obiba_mica_persons_table_headers() {
  return array(
    array("title" => t('Name'), 'data' => 'firstName'),
    array("title" => t('Email'), 'data' => 'email'),
    array("title" => t('Studies'), 'data' => 'studyMemberships[, ].parentId'),
  );
}

/**
 * Create modal DOM for Contacts/investigators.
 *
 * @param $study_id
 * @param $persons
 * @return string
 */
function obiba_mica_persons_get_person_detail($type_person, $study_id, $persons) {
  $page_render_persons = '';
  foreach ($persons as $key_person => $person) {
    $id_person = $type_person . '_' . $study_id . '_' . $key_person;
    $page_render_persons .= theme('mica_person_detail', array(
      'study_id' => $study_id,
      'person_uid' => $id_person,
      'person' => $person,
    ));
  }
  return $page_render_persons;
}
