<?php
/**
 * @file
 * Copyright (c) 2016 OBiBa. All rights reserved.
 *
 * This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Implements hook_menu().
 */
function obiba_mica_research_project_menu() {
  $items = array();

  $items[MicaClientPathProvider::RESEARCH_PROJECT] = array(
    'title' => variable_get('project_approved_page_title', 'Research'),
    'description' => 'Research project',
    'page callback' => 'obiba_mica_research_project_page_list',
    'file' => 'obiba_mica_research_project-page-list.inc',
    'access callback' => TRUE,
    'expanded' => TRUE,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
    'weight' => 5
  );

  $items[MicaClientPathProvider::RESEARCH_PROJECT_APPROVED] = array(
    'title' => variable_get('project_approved_page_title', 'Approved Projects'),
    'description' => 'Approved research projects',
    'access callback' => TRUE,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
    'weight' => 2
  );

  $items['mica/research/project/%'] = array(
    'title' => variable_get('project_page_title', 'Research Project Page'),
    'page callback' => 'obiba_mica_research_project_page_detail',
    'file' => 'obiba_mica_research_project-detail-page.inc',
    'access callback' => TRUE,
    'page arguments' => array(3)
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function obiba_mica_research_project_theme($existing, $type, $theme, $path) {
  $path_theme = $path . '/templates';

  return array(
    'obiba_mica_research_project-list-page' => array(
      'template' => 'obiba_mica_research_project-list-page',
      'path' => $path_theme
    ),  
    'obiba_mica_research_project-list-page-block' => array(
      'template' => 'obiba_mica_research_project-list-page-block',
      'path' => $path_theme
    ),
    'obiba_mica_research_project-detail-page' => array(
      'template' => 'obiba_mica_research_project-detail',
      'path' => $path_theme
    ));
}

/**
 * Implements hook_load_menus().
 */
function obiba_mica_research_project_load_menus() {
  $items = array();
  
  $items[MicaClientPathProvider::RESEARCH_PROJECT] = array(
    'access callback' => TRUE,
    'title' => variable_get('project_approved_page_title', 'Research'),
    'module_caller' => 'obiba_mica_research_project'
  );
  return $items;
}

/**
 * Implements hook_library().
 */
function obiba_mica_research_project_library() {
  return obiba_mica_app_angular_load_angular_library();
}

/**
 * Create/Update research project node content page.
 */
function obiba_mica_research_project() {
  $research_project_node_node = obiba_mica_commons_get_translated_node(variable_get_value('research_project_page'));
  drupal_set_title($research_project_node_node['#node']->title);
  if (!empty($research_project_node_node)) {
    return $research_project_node_node;
  } else {
    $research_project_node_page = obiba_mica_commons_add_page(variable_get_value('research_project_page'), '');
    variable_set('research_project_page', $research_project_node_page->nid);
    return node_view(node_load(variable_get_value('research_project_page')));
  }
}