<?php
/**
 * Copyright (c) 2018 OBiBa. All rights reserved.
 *
 * This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file
 * Obiba Mica Data table file
 */


/**
 * Implements hook_library().
 */
//function obiba_mica_data_table_library() {
//  return obiba_mica_app_angular_load_angular_library();
//}

/**
 * Implements hook_theme().
 *
 * copy '<modules>/obiba_mica_network/templates/'   files in  your customized
 * theme  '<YOUR_THEME>/templates/' path you can modify default display of
 * listed page templates by rearrange block field for example don't forget to
 * clear the theme registry.
 *
 */
//function obiba_mica_data_table_theme($existing, $type, $theme, $path) {
//  $path_theme = $path . '/templates';
////  $path_views_theme = $path . '/js/app/views';
//  return array(
//    'obiba_mica_angular_app_data_table'=> array(
//      'template' => 'obiba_mica_angular_app_data_table',
//      'path' => $path_theme
//    ),
////    'data-table-component' => array(
////      'template' => 'data-table-component',
////      'path' => $path_views_theme
////    ),
//  );
//}

/**
 * Implements hook_get_js().
 */
function obiba_mica_data_table_get_js($weight_js) {
  $module_path = drupal_get_path('module', 'obiba_mica_data_table');
  $js = file_scan_directory($module_path . '/js/app', '/.*\.js$/', array('key' => 'name'));
  ksort($js);
  foreach ($js as $file_js) {
    drupal_add_js($file_js->uri, array(
      'type' => 'file',
      'scope' => 'footer',
      'weight' => ++$weight_js
    ));
  }
  return $weight_js;
}

/**
 * Implements hook_get_ng_module_to_load().
 */
function obiba_mica_data_table_get_ng_module_to_load() {
  return 'mica.obibaDataTable';
}

/**
 * Set Pie charts graphics options
 */
//function obiba_mica_data_table_options_settings() {
//  obiba_mica_data_table_local_options();
//}


/**
 * Get Local charts Options.
 *
 * @param $graphics_options .
 *
 * @return array.
 */
//function obiba_mica_data_table_local_options() {
//  drupal_add_js(array(
//    'dataTableOptions' => array()
//  ),
//    'setting');
//
//}

